In [1]:
import pandas as pd

In [97]:
!uv pip install ipywidgets

Audited 1 package in 12ms

In [22]:
orig = pd.read_csv("gs://foundation-model-data/data/barkley_canyon/BarkleyCanyonAnnotations_Public_Final.csv")
orig.shape

(12763, 22)

In [23]:
orig.columns

Index(['Soundfile', 'Left time (sec)', 'Right time (sec)', 'Top freq (Hz)',
       'Bottom freq (Hz)', 'Species', 'Call Type', 'Ecotype', 'Unnamed: 8',
       'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12',
       'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16',
       'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20',
       'Unnamed: 21'],
      dtype='object')

In [33]:
orig["Call Type"].isnull().sum()

np.int64(3825)

In [50]:
orig = orig.drop(labels=['Unnamed: 8',
       'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12',
       'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16',
       'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20',
       'Unnamed: 21'], axis=1)
orig.shape

(12763, 8)

In [56]:
orig.columns

Index(['Soundfile', 'Left time (sec)', 'Right time (sec)', 'Top freq (Hz)',
       'Bottom freq (Hz)', 'Species', 'Call Type', 'Ecotype'],
      dtype='object')

In [ ]:
orig.sh

In [31]:
orig["Soundfile"].unique().shape

(5254,)

In [52]:
orig["Species"].unique()

array(['Oo', 'Mn', 'BA|Bp', 'BA', 'Bp', 'MY', 'UN|BA', 'UN|DE|Mn',
       'MY|Mn', 'UN|MY|NN', 'UN|MY', 'OD', 'DE|Lo', 'DE|Lb|Lo', 'UN|Mn',
       'DE', 'UN', 'UN|Mn|MY', 'DE|Gg', 'UN|Mn|NN', 'DE|Gg|Lo',
       'DE|Gg|Lb|Lo', 'UN|DE|Lo', 'UN|BA|Bp', 'UN|DE', 'UN|Bp',
       'CE|Mn|Oo', 'CE|Mn', 'MY|Bm', 'MY|Bm|Bp', 'UN|Bm', 'CE|DE',
       'UN|NN|OD', 'NN', 'UN|FI|Mn', 'UN|FI|Mn|NN', 'CE|DE|Mn', 'UN|CE',
       'UN|DE|Oo', 'UN|Mn|Oo', 'UN|Oo', 'DE|Oo', 'UN|NN|OD|Pm', 'UN|Pm',
       'Pm', 'UN|OD|Pm', 'UN|OD', 'UN|Pm|NN', 'UN|NN|Pm', 'UN|DE|NN|OD',
       'Bm', 'UN|NN', 'MY|Er', 'OD|Pm', 'UN|FI', 'UN|DE|OD', 'OD|OOD|Pm',
       'OD|Oo', 'UN|FI|NN|OD', 'UN|DE|NN', 'MY|Ej|Mn', 'MY|Mn|Ej',
       'BA|Bp|Bb', 'Gg', 'UN|Bp|NN', 'UN|FI|NN', 'UN|Ej|NN',
       'UN|BA|FI|NN', 'UN|DE|Mn|NN', 'MY|Er|Mn', 'UN|Er|Mn|NN', 'CE',
       'UN|DE|Gg', 'UN|BA|Bb|Bp', 'UN|Mn|NN|OD', 'AN|Mn', 'DE|Lb|LOD|Oo',
       'AN', 'CE|Mn|DE', 'UN|Mn|OD', 'CE|DE|OD', 'Lo', 'UN|Er|FI',
       'UN|BA|PI', 'UN|BA|NN', 'UN|Er|FI|Mn', 'UN|BA|Er|Mn',
       'UN|BA|FI|PI', 'AN|MY', 'UN|NN|Mn', 'UN||Mn|NN', 'UN|Bm|MY',
       'MY|Ej|Er|Mn', 'UN|FI|MY|NN', 'MY|BBA|Bp|Ej', 'UN|Er|Mn',
       'UN|Bm|Bp', 'UN|Bm|NN', 'MY|BBA|Bp', 'UN|Er', 'CE|DE|OOD|Mn',
       'AN|DE|PI|Mn', 'AN|MY|FI', 'UN|BA|FI', 'DE|Lb', 'DE|Lb|Lo|Oo',
       'UN|DE|Mn|MY', 'CE|Oo', 'UN|BA|FI|OD'], dtype=object)

In [143]:
HIGH_LEVEL_TAXA = {
    "BA", "DE", "MY", "OD", "CE", "PI", "MA", "FI", "AN", "NN"
}

species_map_scientific = {
    "Bm": "Balaenoptera musculus",
    "Bp": "Balaenoptera physalus",
    "Bb": "Balaenoptera borealis",
    "Mn": "Megaptera novaeangliae",
    "Er": "Eschrichtius robustus",
    "Ej": "Eubalaena japonica",
    "Pm": "Physeter macrocephalus",
    "Oo": "Orcinus orca",
    "Gg": "Grampus griseus",
    "Lo": "Lagenorhynchus obliquidens",
    "Lb": "Lissodelphis borealis",
    "BA": "Balaenoptera (Genus)",
    "DE": "Delphinidae (Family of dolphins)",
    "MY": "Mysticeti (Baleen whales)",
    "OD": "Odontoceti (Toothed whales)",
    "CE": "Cetacea (Whales, dolphins, porpoises)",
    "PI": "Pinnipedia (Seals, sea lions, walruses)",
    "MA": "Mammalia (Mammals)",
    "FI": "Fish",
    "AN": "Animalia (Animals)",
    "UN": "Unknown"
}

species_map_common = {
    "Bm": "Blue whale",
    "Bp": "Fin whale",
    "Bb": "Sei whale",
    "Mn": "Humpback whale",
    "Er": "Gray whale",
    "Ej": "North Pacific right whale",
    "Pm": "Sperm whale",
    "Oo": "Killer whale",
    "Gg": "Risso’s dolphin",
    "Lo": "Pacific white-sided dolphin",
    "Lb": "Northern right whale dolphin",
    "BA": "Balaenoptera",
    "DE": "Delphinidae",
    "MY": "Baleen whales",
    "OD": "Toothed whales",
    "CE": "Cetaceans",
    "PI": "Pinnipeds",
    "MA": "Mammals",
    "FI": "Fish",
    "AN": "Animals",
    "UN": "Unknown"
}

call_type_map = {
    "CK": "Click",
    "BZ": "Buzz",
    "W": "Whistle",
    "BP": "Burst-Pulse",
    "S": "Humpback song",
    "NS": "Humpback non-song",
    "A": "Blue whale A call",
    "B": "Blue whale B call",
    "C": "Blue whale C call",
    "D": "Blue whale D call",
    "40 Hz": "Fin whale 40 Hz call",
    "classic": "Fin whale 20Hz call (classic)",
    "backbeat": "Fin whale 20Hz call (backbeat)",
    # "O": "Other call type"
}

In [15]:
df = pd.read_json("gs://foundation-model-data/data/barkley_canyon/barkley_detection_common.jsonl",
                  orient="records", lines=True)

In [20]:
df["path"].iloc[0]

'audio/barkley-detection/ICLISTENHF1251_20130520T003321.072Z_000.wav'

In [21]:
df["answer"].unique()

array(['None', 'Killer whale', 'Humpback whale', 'Fin whale',
       'Fin whale, Humpback whale', 'Sperm whale',
       'Fin whale, Sperm whale', 'Blue whale', 'Fin whale, Killer whale',
       'Risso’s dolphin', 'Humpback whale, Sperm whale',
       'Risso’s dolphin, Sperm whale', 'Humpback whale, Risso’s dolphin',
       'Pacific white-sided dolphin', 'Humpback whale, Killer whale',
       'Humpback whale, Pacific white-sided dolphin',
       'Killer whale, Sperm whale', 'Blue whale, Sperm whale',
       'Blue whale, Humpback whale', 'Blue whale, Risso’s dolphin',
       'Blue whale, Fin whale', 'Blue whale, Fin whale, Humpback whale',
       'Fin whale, Pacific white-sided dolphin',
       'Blue whale, Pacific white-sided dolphin',
       'Fin whale, Humpback whale, Pacific white-sided dolphin'],
      dtype=object)

In [54]:
import duckdb

In [58]:
conn = duckdb.connect("/Users/gagan/esp-ml-datasets/gbif_taxonomy.db")

In [102]:
def get_taxonomy(sci_name: str) -> dict[str, str]:
    query = f"""SELECT TaxonID, Kingdom, Phylum, "Class", "Order", Family, Genus
    FROM gbif WHERE ScientificName = '{sci_name}';"""
    out = conn.sql(query).fetchall()
    if len(out) == 0:
        return None
    out = out[0]
    return {"gbifID": out[0],
            "kingdom": out[1],
            "phylum": out[2],
            "class": out[3],
            "order": out[4],
            "family": out[5],
            "genus": out[6],
           }

In [91]:
get_taxonomy(species_map_scientific["Bm"])

SELECT TaxonID, Kingdom, Phylum, "Class", "Order", Family, Genus
    FROM gbif WHERE ScientificName = 'Balaenoptera musculus';

{'gbifID': 2440735,
 'kingdom': 'Animalia',
 'phylum': 'Chordata',
 'class': 'Mammalia',
 'order': 'Cetacea',
 'family': 'Balaenopteridae',
 'genus': 'Balaenoptera'}

In [59]:
as_val = pd.read_csv("gs://animalspeak2/splits/v1/animalspeak_eval_v1.3.csv", nrows=100)

In [60]:
as_val.shape

(100, 49)

In [61]:
as_val.head(3)

,Associated Taxa,Unnamed: 0,audio_file_name,audio_id,audiocap_id,background_family,background_genus,background_species_common,background_species_sci,background_taxonomic,...,species_scientific_normalized,start_time,subspecies,taxonomic_name,url,youtube_id,country,locality,verbatimElevation,extracted_name
0,NaN,967164.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Poecile montanus,NaN,NaN,Chordata Aves Passeriformes Paridae Poecile mo...,https://xeno-canto.org/sounds/uploaded/ACYAQZY...,NaN,Poland,"Gmina Leoncin (near Górki), nowodworski, mazo...",80 m,NaN
1,NaN,673659.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Himantopus melanurus,NaN,NaN,Chordata Aves Charadriiformes Recurvirostridae...,https://xeno-canto.org/sounds/uploaded/GJDWYMC...,NaN,Argentina,"Claromecó, Tres Arroyos, Buenos Aires",20 m,NaN
2,has background sounds: Cinnyris jugularis,529295.0,NaN,NaN,NaN,Nectariniidae,Cinnyris,Olive-backed Sunbird,Cinnyris jugularis,Chordata Aves Passeriformes Nectariniidae Cinn...,...,Colluricincla rufogaster griseata,NaN,Colluricincla rufogaster griseata,Chordata Aves Passeriformes Pachycephalidae Co...,https://xeno-canto.org/sounds/uploaded/GNEWSLM...,NaN,Australia,"Cassowary House, Kuranda, Queensland, Australia",360 m,NaN

In [62]:
as_val.columns

Index(['Associated Taxa', 'Unnamed: 0', 'audio_file_name', 'audio_id',
       'audiocap_id', 'background_family', 'background_genus',
       'background_species_common', 'background_species_sci',
       'background_taxonomic', 'behavior', 'canonical_name', 'caption',
       'caption2', 'caption3', 'class', 'eventDate', 'eventTime', 'family',
       'fieldNotes', 'gbifID', 'genus', 'identifier', 'latitudeDecimal',
       'license', 'license_url', 'lifeStage', 'local_path', 'longitudeDecimal',
       'order', 'path', 'phylum', 'recordist', 'rightsHolder', 'sex', 'source',
       'species', 'species_common', 'species_scientific',
       'species_scientific_normalized', 'start_time', 'subspecies',
       'taxonomic_name', 'url', 'youtube_id', 'country', 'locality',
       'verbatimElevation', 'extracted_name'],
      dtype='object')

In [135]:
TT = as_val["taxonomic_name"].sample(n=20)
TT.iloc[0]

'Chordata Aves Passeriformes Passerellidae Zonotrichia leucophrys'

# Loop over barkley canyon dataset and add taxonomy

In [75]:
orig.shape

(12763, 8)

In [121]:
from tqdm.notebook import tqdm

In [117]:
pd.NA

In [120]:
import ipywidgets

In [144]:
taxonomy = {"gbifID": [],
            "kingdom": [],
            "phylum": [],
            "class": [],
            "order": [],
            "family": [],
            "genus": [],
            "species_common": [],
            "species_scientific": [],
            "taxonomic_name": []}

for i, row in tqdm(orig.iterrows(), total=len(orig)):
    detected_species = row["Species"].split("|")

    gbifID = []
    kingdom = []
    phylum = []
    _class = []
    order = []
    family = []
    genus = []
    species_common = []
    species_scientific = []
    taxonomic_name = []
    
    for d in detected_species:
        
        if d in HIGH_LEVEL_TAXA:
            species_sci = "Unknown"
            species_comm = "Unknown"
            
            species_common.append(species_comm)
            species_scientific.append(species_sci)
            continue
            
        else:
            species_sci = species_map_scientific.get(d, "Unknown")
            species_comm = species_map_common.get(d, "Unknown")
        
            species_common.append(species_comm)
            species_scientific.append(species_sci)
        
        tax = get_taxonomy(species_sci)
        if tax is None:
            continue
        taxname = tax["phylum"] + " "  + tax["class"] + " " + tax["order"] + " " + tax["family"] + " " + tax["genus"]
        
        gbifID.append(tax["gbifID"])
        kingdom.append(tax["kingdom"])
        phylum.append(tax["phylum"])
        _class.append(tax["class"])
        order.append(tax["order"])
        family.append(tax["family"])
        genus.append(tax["genus"])
        taxonomic_name.append(taxname)

    taxonomy["gbifID"].append(gbifID or pd.NA)
    taxonomy["kingdom"].append(",".join(kingdom) or pd.NA)
    taxonomy["phylum"].append(",".join(phylum) or pd.NA)
    taxonomy["class"].append(",".join(_class) or pd.NA)
    taxonomy["order"].append(",".join(order) or pd.NA)
    taxonomy["family"].append(",".join(family) or pd.NA)
    taxonomy["genus"].append(",".join(genus) or pd.NA)
    taxonomy["species_common"].append(",".join(species_common))
    taxonomy["species_scientific"].append(",".join(species_scientific))
    taxonomy["taxonomic_name"].append(",".join(taxonomic_name) or pd.NA)

  0%|          | 0/12763 [00:00<?, ?it/s]

In [145]:
len(taxonomy["genus"])

12763

In [146]:
taxonomy = pd.DataFrame(taxonomy)

In [150]:
taxonomy.sample(n=10, replace=True)

,gbifID,kingdom,phylum,class,order,family,genus,species_common,species_scientific,taxonomic_name
10506,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,"Unknown,Unknown","Unknown,Unknown",<NA>
9606,[5220069],Animalia,Chordata,Mammalia,Cetacea,Delphinidae,Lagenorhynchus,Pacific white-sided dolphin,Lagenorhynchus obliquidens,Chordata Mammalia Cetacea Delphinidae Lagenorh...
2502,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Unknown,Unknown,<NA>
6375,[8123917],Animalia,Chordata,Mammalia,Cetacea,Physeteridae,Physeter,Sperm whale,Physeter macrocephalus,Chordata Mammalia Cetacea Physeteridae Physeter
1647,[5220069],Animalia,Chordata,Mammalia,Cetacea,Delphinidae,Lagenorhynchus,"Unknown,Pacific white-sided dolphin","Unknown,Lagenorhynchus obliquidens",Chordata Mammalia Cetacea Delphinidae Lagenorh...
9455,[9809568],Animalia,Chordata,Mammalia,Cetacea,Balaenopteridae,Megaptera,Humpback whale,Megaptera novaeangliae,Chordata Mammalia Cetacea Balaenopteridae Mega...
2145,"[2440467, 5220069]","Animalia,Animalia","Chordata,Chordata","Mammalia,Mammalia","Cetacea,Cetacea","Delphinidae,Delphinidae","Lissodelphis,Lagenorhynchus","Unknown,Northern right whale dolphin,Pacific w...","Unknown,Lissodelphis borealis,Lagenorhynchus o...",Chordata Mammalia Cetacea Delphinidae Lissodel...
8484,"[2440467, 5220069]","Animalia,Animalia","Chordata,Chordata","Mammalia,Mammalia","Cetacea,Cetacea","Delphinidae,Delphinidae","Lissodelphis,Lagenorhynchus","Unknown,Northern right whale dolphin,Pacific w...","Unknown,Lissodelphis borealis,Lagenorhynchus o...",Chordata Mammalia Cetacea Delphinidae Lissodel...
11711,[9809568],Animalia,Chordata,Mammalia,Cetacea,Balaenopteridae,Megaptera,Humpback whale,Megaptera novaeangliae,Chordata Mammalia Cetacea Balaenopteridae Mega...
1038,[9809568],Animalia,Chordata,Mammalia,Cetacea,Balaenopteridae,Megaptera,Humpback whale,Megaptera novaeangliae,Chordata Mammalia Cetacea Balaenopteridae Mega...

In [138]:
taxonomy["taxonomic_name"].iloc[-2]

'Chordata Mammalia Cetacea Balaenopteridae Balaenoptera'

In [151]:
orig_tax = pd.concat([orig, taxonomy], axis=1)
orig_tax.shape

(12763, 18)

In [152]:
orig_tax.to_csv("barkley_canyon_annotations.csv", index=False)

In [106]:
shard_ids[-1]

10599

In [108]:
np.setdiff1d(np.arange(len(shards)), np.array(shard_ids))

array([497, 498, 499, 500, 501, 502, 503, 504, 505, 506, 507, 508, 509,
       510, 511, 512, 513, 514, 515, 516, 517, 518, 519])

In [153]:
orig_tax.columns

Index(['Soundfile', 'Left time (sec)', 'Right time (sec)', 'Top freq (Hz)',
       'Bottom freq (Hz)', 'Species', 'Call Type', 'Ecotype', 'gbifID',
       'kingdom', 'phylum', 'class', 'order', 'family', 'genus',
       'species_common', 'species_scientific', 'taxonomic_name'],
      dtype='object')

In [156]:
orig_tax_non_null = orig_tax.dropna(how="any", axis=0, subset="gbifID")

In [157]:
orig_tax_non_null.shape

(9782, 18)

In [159]:
orig_tax_non_null.to_csv("barkley_canyon_annotations_non_null_gbif.csv", index=False)

In [160]:
conn.close()

# Redo paths

In [2]:
df = pd.read_csv("barkley_canyon/barkley_canyon_annotations_non_null_gbif.csv")

In [3]:
df.columns

Index(['Soundfile', 'Left time (sec)', 'Right time (sec)', 'Top freq (Hz)',
       'Bottom freq (Hz)', 'Species', 'Call Type', 'Ecotype', 'gbifID',
       'kingdom', 'phylum', 'class', 'order', 'family', 'genus',
       'species_common', 'species_scientific', 'taxonomic_name'],
      dtype='object')

In [4]:
df["Soundfile"].iloc[0]

'ICLISTENHF1251_20130520T003321.072Z.wav'

In [5]:
df["local_path"] = ["audio/" + x for x in df["Soundfile"].tolist()]

In [6]:
df.columns

Index(['Soundfile', 'Left time (sec)', 'Right time (sec)', 'Top freq (Hz)',
       'Bottom freq (Hz)', 'Species', 'Call Type', 'Ecotype', 'gbifID',
       'kingdom', 'phylum', 'class', 'order', 'family', 'genus',
       'species_common', 'species_scientific', 'taxonomic_name', 'local_path'],
      dtype='object')

In [9]:
df.to_csv("barkley_canyon/barkley_canyon_annotations_non_null_gbif.csv", index=False)

In [7]:
df2 = pd.read_csv("barkley_canyon/barkley_canyon_annotations.csv")

In [8]:
df2["local_path"] = ["audio/" + x for x in df2["Soundfile"].tolist()]

In [10]:
df2.to_csv("barkley_canyon/barkley_canyon_annotations.csv", index=False)