In [1]:
from esp_data import Beans, BirdSet

In [10]:
import pandas as pd
from esp_data.io import anypath

# Fix BEANS

What we want is to introduce a new column called `labels_as_list` that maps the label column as a list of str (or int or Any) rather than a comma separated list of strings.

In [3]:
beans = Beans(split="train")

In [6]:
splits = Beans.info.split_paths

In [7]:
splits

{'train': 'gs://esp-ml-datasets/beans/v0.1.0/raw/beans_train.csv',
 'validation': 'gs://esp-ml-datasets/beans/v0.1.0/raw/beans_val.csv',
 'test': 'gs://esp-ml-datasets/beans/v0.1.0/raw/beans_test.csv',
 'cbi_test': 'gs://esp-ml-datasets/beans/v0.1.0/raw/cbi_test.jsonl',
 'cbi_validation': 'gs://esp-ml-datasets/beans/v0.1.0/raw/cbi_val.jsonl',
 'cbi_train': 'gs://esp-ml-datasets/beans/v0.1.0/raw/cbi_train.jsonl',
 'watkins_test': 'gs://esp-ml-datasets/beans/v0.1.0/raw/watkins_test.jsonl',
 'watkins_validation': 'gs://esp-ml-datasets/beans/v0.1.0/raw/watkins_val.jsonl',
 'watkins_train': 'gs://esp-ml-datasets/beans/v0.1.0/raw/watkins_train.jsonl',
 'dogs_test': 'gs://esp-ml-datasets/beans/v0.1.0/raw/dogs_test.jsonl',
 'dogs_validation': 'gs://esp-ml-datasets/beans/v0.1.0/raw/dogs_val.jsonl',
 'dogs_train': 'gs://esp-ml-datasets/beans/v0.1.0/raw/dogs_train.jsonl',
 'egyptian_fruit_bats_test': 'gs://esp-ml-datasets/beans/v0.1.0/raw/egyptian_fruit_bats_test.jsonl',
 'egyptian_fruit_bats_validation': 'gs://esp-ml-datasets/beans/v0.1.0/raw/egyptian_fruit_bats_val.jsonl',
 'egyptian_fruit_bats_train': 'gs://esp-ml-datasets/beans/v0.1.0/raw/egyptian_fruit_bats_train.jsonl',
 'hiceas_test': 'gs://esp-ml-datasets/beans/v0.1.0/raw/hiceas_test.jsonl',
 'hiceas_validation': 'gs://esp-ml-datasets/beans/v0.1.0/raw/hiceas_val.jsonl',
 'hiceas_train': 'gs://esp-ml-datasets/beans/v0.1.0/raw/hiceas_train.jsonl',
 'dcase_test': 'gs://esp-ml-datasets/beans/v0.1.0/raw/dcase_test.jsonl',
 'dcase_validation': 'gs://esp-ml-datasets/beans/v0.1.0/raw/dcase_val.jsonl',
 'dcase_train': 'gs://esp-ml-datasets/beans/v0.1.0/raw/dcase_train.jsonl',
 'enabirds_test': 'gs://esp-ml-datasets/beans/v0.1.0/raw/enabirds_test.jsonl',
 'enabirds_validation': 'gs://esp-ml-datasets/beans/v0.1.0/raw/enabirds_val.jsonl',
 'enabirds_train': 'gs://esp-ml-datasets/beans/v0.1.0/raw/enabirds_train.jsonl',
 'esc50_test': 'gs://esp-ml-datasets/beans/v0.1.0/raw/esc50_test.jsonl',
 'esc50_validation': 'gs://esp-ml-datasets/beans/v0.1.0/raw/esc50_val.jsonl',
 'esc50_train': 'gs://esp-ml-datasets/beans/v0.1.0/raw/esc50_train.jsonl',
 'speech_commands_test': 'gs://esp-ml-datasets/beans/v0.1.0/raw/speech_commands_test.jsonl',
 'speech_commands_validation': 'gs://esp-ml-datasets/beans/v0.1.0/raw/speech_commands_val.jsonl',
 'speech_commands_train': 'gs://esp-ml-datasets/beans/v0.1.0/raw/speech_commands_train.jsonl',
 'humbugdb_test': 'gs://esp-ml-datasets/beans/v0.1.0/raw/humbugdb_test.jsonl',
 'humbugdb_validation': 'gs://esp-ml-datasets/beans/v0.1.0/raw/humbugdb_val.jsonl',
 'humbugdb_train': 'gs://esp-ml-datasets/beans/v0.1.0/raw/humbugdb_train.jsonl',
 'rfcx_test': 'gs://esp-ml-datasets/beans/v0.1.0/raw/rfcx_test.jsonl',
 'rfcx_validation': 'gs://esp-ml-datasets/beans/v0.1.0/raw/rfcx_val.jsonl',
 'rfcx_train': 'gs://esp-ml-datasets/beans/v0.1.0/raw/rfcx_train.jsonl',
 'hainan_gibbons_test': 'gs://esp-ml-datasets/beans/v0.1.0/raw/hainan_gibbons_test.jsonl',
 'hainan_gibbons_validation': 'gs://esp-ml-datasets/beans/v0.1.0/raw/hainan_gibbons_val.jsonl',
 'hainan_gibbons_train': 'gs://esp-ml-datasets/beans/v0.1.0/raw/hainan_gibbons_train.jsonl'}

In [12]:
beans._data.head(5)

    label     file_name                  local_path source_dataset
0  aldfly  XC135454.wav  audio/cbi/wav/XC135454.wav            cbi
1  aldfly  XC135455.wav  audio/cbi/wav/XC135455.wav            cbi
2  aldfly  XC135456.wav  audio/cbi/wav/XC135456.wav            cbi
3  aldfly  XC135457.wav  audio/cbi/wav/XC135457.wav            cbi
4  aldfly  XC135459.wav  audio/cbi/wav/XC135459.wav            cbi

In [50]:
def to_list(x):
    if not x or pd.isnull(x):
        return []
    if isinstance(x, str):
        label = x.split(",")
        return [x.strip() for x in label]

    if isinstance(x, int):
        return [x]

    raise TypeError("Unrecognized type")

In [14]:
beans._data.loc[:, "label"] = beans._data["label"].apply(to_list)

### Run to_fly

In [23]:
data_frames = {}

In [ ]:
for k, v in splits.items():

    if k in data_frames:
        continue
        
    df = Beans(split=k)._data
    if "label" in df:
        df["labels_as_list"] = df.label.apply(to_list)
    elif "answer" in df:
        df["labels_as_list"] = df.answer.apply(to_list)
        
    data_frames[k] = df

    print(f"Done with split {k}")

In [20]:
k

'hiceas_test'

In [22]:
df.head(4)

                     answer  ...                                     local_path
0  Minke Whale 'boing' call  ...  audio/hiceas/1705_20171118_033936_019_000.wav
1  Minke Whale 'boing' call  ...  audio/hiceas/1705_20171118_033936_019_001.wav
2                      None  ...  audio/hiceas/1705_20171118_033936_019_002.wav
3                      None  ...  audio/hiceas/1705_20171118_033936_019_003.wav

[4 rows x 3 columns]

In [37]:
data_frames["watkins_train"].sample(n=10)

                                label  ...                      labels_as_list
689  Short-Finned_Pacific_Pilot_Whale  ...  [Short-Finned_Pacific_Pilot_Whale]
859           Long-Finned_Pilot_Whale  ...           [Long-Finned_Pilot_Whale]
991                    Common_Dolphin  ...                    [Common_Dolphin]
768                False_Killer_Whale  ...                [False_Killer_Whale]
453           Grampus,_Rissos_Dolphin  ...          [Grampus, _Rissos_Dolphin]
112                   Spinner_Dolphin  ...                   [Spinner_Dolphin]
490          Atlantic_Spotted_Dolphin  ...          [Atlantic_Spotted_Dolphin]
911                   Striped_Dolphin  ...                   [Striped_Dolphin]
966                       Sperm_Whale  ...                       [Sperm_Whale]
529                Fin,_Finback_Whale  ...               [Fin, _Finback_Whale]

[10 rows x 4 columns]

In [38]:
data_frames["watkins_train"].iloc[453].to_dict()

{'label': 'Grampus,_Rissos_Dolphin',
 'file_name': '59030023.wav',
 'local_path': 'audio/watkins/59030023.wav',
 'labels_as_list': ['Grampus', '_Rissos_Dolphin']}

In [42]:
len(data_frames)

39

## Save

In [ ]:
for k, df in data_frames.items():

    print(f"Saving split {k}")
    # get split address
    path = anypath(splits[k])
    
    if path.suffix == ".csv":
        df.to_csv(str(path), index=False)
    elif path.suffix == ".jsonl":
        df.to_json(str(path), lines=True, orient="records")

    print(f"Saved split {k}")

# Fix BirdSet

Same as above

In [46]:
birdset_splits = BirdSet.info.split_paths

In [47]:
birdset_splits

{'HSN-train': 'gs://foundation-model-data/data/birdset-train/HSN/HSN_taxonomic.jsonl',
 'HSN-validation': 'gs://foundation-model-data/data/birdset-train/HSN/HSN_taxonomic.jsonl',
 'HSN-test': 'gs://foundation-model-data/data/birdset-test/HSN/HSN_taxonomic.jsonl',
 'NBP-train': 'gs://foundation-model-data/data/birdset-train/NBP/NBP_taxonomic.jsonl',
 'NBP-validation': 'gs://foundation-model-data/data/birdset-train/NBP/NBP_taxonomic.jsonl',
 'NBP-test': 'gs://foundation-model-data/data/birdset-test/NBP/NBP_taxonomic.jsonl',
 'NES-train': 'gs://foundation-model-data/data/birdset-train/NES/NES_taxonomic.jsonl',
 'NES-validation': 'gs://foundation-model-data/data/birdset-train/NES/NES_taxonomic.jsonl',
 'NES-test': 'gs://foundation-model-data/data/birdset-test/NES/NES_taxonomic.jsonl',
 'PER-train': 'gs://foundation-model-data/data/birdset-train/PER/PER_taxonomic.jsonl',
 'PER-validation': 'gs://foundation-model-data/data/birdset-train/PER/PER_taxonomic.jsonl',
 'PER-test': 'gs://foundation-model-data/data/birdset-test/PER/PER_taxonomic.jsonl',
 'POW-train': 'gs://foundation-model-data/data/birdset-train/POW/POW_taxonomic.jsonl',
 'POW-validation': 'gs://foundation-model-data/data/birdset-train/POW/POW_taxonomic.jsonl',
 'POW-test': 'gs://foundation-model-data/data/birdset-test/POW/POW_taxonomic.jsonl'}

In [48]:
powtest = BirdSet(split="POW-train")

In [49]:
powtest._data.sample(n=10)

                                        path  ...                                             prompt
1768   audio/birdset-train/POW/XC254719.flac  ...  <Audio><AudioHere></Audio> What are the taxono...
5120   audio/birdset-train/POW/XC370670.flac  ...  <Audio><AudioHere></Audio> What are the taxono...
3638   audio/birdset-train/POW/XC415057.flac  ...  <Audio><AudioHere></Audio> What are the taxono...
11410  audio/birdset-train/POW/XC734886.flac  ...  <Audio><AudioHere></Audio> What are the taxono...
10671  audio/birdset-train/POW/XC175543.flac  ...  <Audio><AudioHere></Audio> What are the taxono...
6801   audio/birdset-train/POW/XC764935.flac  ...  <Audio><AudioHere></Audio> What are the taxono...
4518   audio/birdset-train/POW/XC523652.flac  ...  <Audio><AudioHere></Audio> What are the taxono...
285    audio/birdset-train/POW/XC314260.flac  ...  <Audio><AudioHere></Audio> What are the taxono...
12635  audio/birdset-train/POW/XC516376.flac  ...  <Audio><AudioHere></Audio> What are the taxono...
9355   audio/birdset-train/POW/XC168965.flac  ...  <Audio><AudioHere></Audio> What are the taxono...

[10 rows x 4 columns]

In [51]:
birdsetdata_frames = {}

In [52]:
for k, v in birdset_splits.items():
    
    print(f"Working on split {k}")
    if k in birdsetdata_frames:
        continue
        
    df = BirdSet(split=k)._data
    if "label" in df:
        df["labels_as_list"] = df.label.apply(to_list)
    elif "label" not in df and "text" in df:
        df["labels_as_list"] = df.text.apply(to_list)
        
    birdsetdata_frames[k] = df

    print(f"Done with split {k}")

Working on split HSN-train
Done with split HSN-train
Working on split HSN-validation
Done with split HSN-validation
Working on split HSN-test
Done with split HSN-test
Working on split NBP-train
Done with split NBP-train
Working on split NBP-validation
Done with split NBP-validation
Working on split NBP-test
Done with split NBP-test
Working on split NES-train
Done with split NES-train
Working on split NES-validation
Done with split NES-validation
Working on split NES-test
Done with split NES-test
Working on split PER-train
Done with split PER-train
Working on split PER-validation
Done with split PER-validation
Working on split PER-test
Done with split PER-test
Working on split POW-train
Done with split POW-train
Working on split POW-validation
Done with split POW-validation
Working on split POW-test
Done with split POW-test

In [55]:
birdsetdata_frames["PER-train"].sample(n=10)

                                        path  ...                                     labels_as_list
2617   audio/birdset-train/PER/XC409377.flac  ...        [Trogoniformes Trogonidae Trogon melanurus]
468     audio/birdset-train/PER/XC74714.flac  ...    [Tinamiformes Tinamidae Crypturellus undulatus]
5555   audio/birdset-train/PER/XC443234.flac  ...  [Passeriformes Furnariidae Sittasomus griseica...
6309   audio/birdset-train/PER/XC171588.flac  ...      [Psittaciformes Psittacidae Amazona farinosa]
15173  audio/birdset-train/PER/XC477092.flac  ...   [Passeriformes Thraupidae Saltator coerulescens]
11493  audio/birdset-train/PER/XC303423.flac  ...  [Passeriformes Tyrannidae Platyrinchus platyrh...
14807  audio/birdset-train/PER/XC727459.flac  ...        [Passeriformes Thraupidae Saltator maximus]
7851   audio/birdset-train/PER/XC524218.flac  ...  [Passeriformes Thamnophilidae Myrmophylax atro...
15419   audio/birdset-train/PER/XC82169.flac  ...  [Passeriformes Troglodytidae Campylorhynchus t...
14083  audio/birdset-train/PER/XC431828.flac  ...       [Passeriformes Thraupidae Tangara chilensis]

[10 rows x 5 columns]

In [56]:
birdsetdata_frames["PER-train"].iloc[7851].to_dict()

{'path': 'audio/birdset-train/PER/XC524218.flac',
 'label': 'Passeriformes Thamnophilidae Myrmophylax atrothorax',
 'text': 'Passeriformes Thamnophilidae Myrmophylax atrothorax',
 'prompt': '<Audio><AudioHere></Audio> What are the taxonomic names for the focal species in the audio, if any?',
 'labels_as_list': ['Passeriformes Thamnophilidae Myrmophylax atrothorax']}

In [57]:
for k, df in birdsetdata_frames.items():
    for i, row in df.iterrows():
        if len(row["labels_as_list"]) > 1:
            print(row["labels_as_list"])
            break

['Passeriformes Troglodytidae Salpinctes obsoletus', 'Passeriformes Passerellidae Zonotrichia leucophrys']
['Passeriformes Muscicapidae Luscinia megarhynchos', 'Passeriformes Paridae Cyanistes caeruleus']
['Apodiformes Trochilidae Saucerottia saucerottei', 'Passeriformes Icteridae Icterus chrysater']
['Passeriformes Cardinalidae Cyanoloxia rothschildii', 'Passeriformes Turdidae Turdus hauxwelli', 'Tinamiformes Tinamidae Crypturellus soui', 'Columbiformes Columbidae Patagioenas subvinacea']
['Passeriformes Paridae Poecile atricapillus', 'Passeriformes Turdidae Turdus migratorius', 'Passeriformes Passerellidae Pipilo erythrophthalmus', 'Passeriformes Cardinalidae Cardinalis cardinalis', 'Passeriformes Parulidae Mniotilta varia']

## Save

In [58]:
for k, df in birdsetdata_frames.items():

    print(f"Saving split {k}")
    # get split address
    path = anypath(birdset_splits[k])
    
    if path.suffix == ".csv":
        df.to_csv(str(path), index=False)
    elif path.suffix == ".jsonl":
        df.to_json(str(path), lines=True, orient="records")

    print(f"Saved split {k}")

Saving split HSN-train
Saved split HSN-train
Saving split HSN-validation
Saved split HSN-validation
Saving split HSN-test
Saved split HSN-test
Saving split NBP-train
Saved split NBP-train
Saving split NBP-validation
Saved split NBP-validation
Saving split NBP-test
Saved split NBP-test
Saving split NES-train
Saved split NES-train
Saving split NES-validation
Saved split NES-validation
Saving split NES-test
Saved split NES-test
Saving split PER-train
Saved split PER-train
Saving split PER-validation
Saved split PER-validation
Saving split PER-test
Saved split PER-test
Saving split POW-train
Saved split POW-train
Saving split POW-validation
Saved split POW-validation
Saving split POW-test
Saved split POW-test

## Check again

In [59]:
powtest = BirdSet(split="POW-train")

In [60]:
powtest.columns

['path', 'label', 'text', 'prompt', 'labels_as_list']