In [1]:
import pandas as pd
import numpy as np
import os
from pathlib import Path
import duckdb

In [2]:
import json

In [3]:
df = pd.read_json("barkley_detection_common.jsonl", orient="records", lines=True)

In [4]:
df.shape

(308865, 3)

In [5]:
df.head(10)

,instruction,path,answer
0,{barkley-detection-common},audio/barkley-detection/ICLISTENHF1251_2013052...,None
1,{barkley-detection-common},audio/barkley-detection/ICLISTENHF1251_2013052...,None
2,{barkley-detection-common},audio/barkley-detection/ICLISTENHF1251_2013052...,None
3,{barkley-detection-common},audio/barkley-detection/ICLISTENHF1251_2013052...,None
4,{barkley-detection-common},audio/barkley-detection/ICLISTENHF1251_2013052...,None
5,{barkley-detection-common},audio/barkley-detection/ICLISTENHF1251_2013052...,None
6,{barkley-detection-common},audio/barkley-detection/ICLISTENHF1251_2013052...,None
7,{barkley-detection-common},audio/barkley-detection/ICLISTENHF1251_2013052...,None
8,{barkley-detection-common},audio/barkley-detection/ICLISTENHF1251_2013052...,None
9,{barkley-detection-common},audio/barkley-detection/ICLISTENHF1251_2013052...,None

In [6]:
df["answer"].unique()

array(['None', 'Killer whale', 'Humpback whale', 'Fin whale',
       'Fin whale, Humpback whale', 'Sperm whale',
       'Fin whale, Sperm whale', 'Blue whale', 'Fin whale, Killer whale',
       'Risso’s dolphin', 'Humpback whale, Sperm whale',
       'Risso’s dolphin, Sperm whale', 'Humpback whale, Risso’s dolphin',
       'Pacific white-sided dolphin', 'Humpback whale, Killer whale',
       'Humpback whale, Pacific white-sided dolphin',
       'Killer whale, Sperm whale', 'Blue whale, Sperm whale',
       'Blue whale, Humpback whale', 'Blue whale, Risso’s dolphin',
       'Blue whale, Fin whale', 'Blue whale, Fin whale, Humpback whale',
       'Fin whale, Pacific white-sided dolphin',
       'Blue whale, Pacific white-sided dolphin',
       'Fin whale, Humpback whale, Pacific white-sided dolphin'],
      dtype=object)

# Add taxonomy

## Use taxonomy which was already computed in the other csv

In [7]:
bc = pd.read_csv("barkley_canyon_annotations_non_null_gbif_v2.csv")

In [8]:
bc.columns

Index(['Soundfile', 'Top freq (Hz)', 'Bottom freq (Hz)', 'Species',
       'Call Type', 'Ecotype', 'gbifID', 'kingdom', 'phylum', 'class', 'order',
       'family', 'genus', 'species_common', 'species_scientific',
       'taxonomic_name', 'local_path', 'start_times(sec)', 'end_times(sec)'],
      dtype='object')

In [38]:
bc.sample(n=50)

,Soundfile,Top freq (Hz),Bottom freq (Hz),Species,Call Type,Ecotype,gbifID,kingdom,phylum,class,order,family,genus,species_common,species_scientific,taxonomic_name,local_path,start_times(sec),end_times(sec)
3786,ICLISTENHF1251_20140401T165458.941Z.wav,2577.61,770.80,Oo,BP,NaN,[2440483],Animalia,Chordata,Mammalia,Cetacea,Delphinidae,Orcinus,Killer whale,Orcinus orca,Chordata Mammalia Cetacea Delphinidae Orcinus ...,audio/ICLISTENHF1251_20140401T165458.941Z.wav,263.650190,265.285160
6704,ICLISTENHF1251_20140904T125409.210Z.wav,37.94,17.03,UN|Bm,NaN,NaN,[2440735],Animalia,Chordata,Mammalia,Cetacea,Balaenopteridae,Balaenoptera,Blue whale,Balaenoptera musculus,Chordata Mammalia Cetacea Balaenopteridae Bala...,audio/ICLISTENHF1251_20140904T125409.210Z.wav,104.752850,113.155890
3054,ICLISTENHF1251_20140204T135224.865Z.wav,487.20,245.17,Mn,S,NaN,[9809568],Animalia,Chordata,Mammalia,Cetacea,Balaenopteridae,Megaptera,Humpback whale,Megaptera novaeangliae,Chordata Mammalia Cetacea Balaenopteridae Mega...,audio/ICLISTENHF1251_20140204T135224.865Z.wav,16.958160,19.315590
4769,ICLISTENHF1251_20140702T003216.335Z.wav,773.10,62.90,UN|Mn,NaN,NaN,[9809568],Animalia,Chordata,Mammalia,Cetacea,Balaenopteridae,Megaptera,Humpback whale,Megaptera novaeangliae,Chordata Mammalia Cetacea Balaenopteridae Mega...,audio/ICLISTENHF1251_20140702T003216.335Z.wav,103.917000,104.733000
8306,ICLISTENHF1251_20141104T140031.845Z.wav,770.80,366.48,Mn,S,NaN,[9809568],Animalia,Chordata,Mammalia,Cetacea,Balaenopteridae,Megaptera,Humpback whale,Megaptera novaeangliae,Chordata Mammalia Cetacea Balaenopteridae Mega...,audio/ICLISTENHF1251_20141104T140031.845Z.wav,25.019010,26.463880
1720,ICLISTENHF1251_20140103T181200.449Z.wav,572.17,204.13,Mn,S,NaN,[9809568],Animalia,Chordata,Mammalia,Cetacea,Balaenopteridae,Megaptera,Humpback whale,Megaptera novaeangliae,Chordata Mammalia Cetacea Balaenopteridae Mega...,audio/ICLISTENHF1251_20140103T181200.449Z.wav,134.346950,135.934350
3280,ICLISTENHF1251_20140301T173327.586Z.wav,8958.02,733.74,Oo,NaN,NaN,[2440483],Animalia,Chordata,Mammalia,Cetacea,Delphinidae,Orcinus,Killer whale,Orcinus orca,Chordata Mammalia Cetacea Delphinidae Orcinus ...,audio/ICLISTENHF1251_20140301T173327.586Z.wav,111.071910,113.315250
4061,ICLISTENHF1251_20140501T000349.292Z.wav,8389.51,527.22,Pm,NaN,NaN,[8123917],Animalia,Chordata,Mammalia,Cetacea,Physeteridae,Physeter,Sperm whale,Physeter macrocephalus,Chordata Mammalia Cetacea Physeteridae Physete...,audio/ICLISTENHF1251_20140501T000349.292Z.wav,105.209130,106.045630
1877,ICLISTENHF1251_20140104T053200.573Z.wav,24638.34,6778.43,DE|Lb|Lo,BP,NaN,"[2440467, 5220069]","Animalia,Animalia","Chordata,Chordata","Mammalia,Mammalia","Cetacea,Cetacea","Delphinidae,Delphinidae","Lissodelphis,Lagenorhynchus","Northern right whale dolphin,Pacific white-sid...","Lissodelphis borealis,Lagenorhynchus obliquidens","Chordata,Chordata Mammalia,Mammalia Cetacea,Ce...",audio/ICLISTENHF1251_20140104T053200.573Z.wav,79.266263,79.742810
294,ICLISTENHF1251_20130623T075500.116Z.wav,5959.28,678.75,Oo,BP,BKW,[2440483],Animalia,Chordata,Mammalia,Cetacea,Delphinidae,Orcinus,Killer whale,Orcinus orca,Chordata Mammalia Cetacea Delphinidae Orcinus ...,audio/ICLISTENHF1251_20130623T075500.116Z.wav,208.609910,209.767940
4438,ICLISTENHF1251_20140601T023134.220Z.wav,12788.93,2847.26,Pm,CK,NaN,[8123917],Animalia,Chordata,Mammalia,Cetacea,Physeteridae,Physeter,Sperm whale,Physeter macrocephalus,Chordata Mammalia Cetacea Physeteridae Physete...,audio/ICLISTENHF1251_20140601T023134.220Z.wav,219.809890,220.608370
8453,ICLISTENHF1251_20141201T010338.988Z.wav,48.80,25.80,UN|Bm,NaN,NaN,[2440735],Animalia,Chordata,Mammalia,Cetacea,Balaenopteridae,Balaenoptera,Blue whale,Balaenoptera musculus,Chordata Mammalia Cetacea Balaenopteridae Bala...,audio/ICLISTENHF1251_20141201T010338.988Z.wav,227.630000,245.400000
6742,ICLISTENHF1251_20140904T154409.240Z.wav,3625.89,288.04,Mn,NS,NaN,[9809568],Animalia,Chordata,Mammalia,Cetacea,Balaenopteridae,Megaptera,Humpback whale,Megaptera novaeangliae,Chordata Mammalia Cetacea Balaenopteridae Mega...,audio/ICLISTENHF1251_20140904T154409.240Z.wav,6.920152,8.441065
2169,ICLISTENHF1251_20140104T181150.142Z.wav,776.73,256.76,Mn,S,NaN,[9809568],Animalia,Chordata,Mammalia,Cetacea,Balaenopteridae,Megaptera,Humpback whale,Megaptera novaeangliae,Chordata Mammalia Cetacea Balaenopteridae Mega...,audio/ICLISTENHF1251_20140104T181150.142Z.wav,29.277570,31.863120
4981,ICLISTENHF1251_20140703T074216.678Z.wav,8389.51,4616.27,DE|Lb|Lo,BP,NaN,"[2440467, 5220069]","Animalia,Animalia","Chordata,Chordata","Mammalia,Mammalia","Cetacea,Cetacea","Delphinidae,Delphinidae","Lissodelphis,Lagenorhynchus","Northern right whale dolphin,Pacific white-sid...","Lissodelphis borealis,Lagenorhynchus obliquidens","Chordata,Chordata Mammalia,Mammalia Cetacea,Ce...",audio/ICLISTENHF1251_20140703T074216.678Z.wav,116.996190,118.022810
6259,ICLISTENHF1251_20140903T084408.901Z.wav,31999.00,21798.40,Gg,CK,NaN,[5220027],Animalia,Chordata,Mammalia,Cetacea,Delphinidae,Grampus,Risso’s dolphin,Grampus griseus,Chordata Mammalia Cetacea Delphinidae Grampus ...,audio/ICLISTENHF1251_20140903T084408.901Z.wav,37.588000,37.655000
1454,ICLISTENHF1251_20140102T185200.190Z.wav,555.90,261.60,Mn,S,NaN,[9809568],Animalia,Chordata,Mammalia,Cetacea,Balaenopteridae,Megaptera,Humpback whale,Megaptera novaeangliae,Chordata Mammalia Cetacea Balaenopteridae Mega...,audio/ICLISTENHF1251_20140102T185200.190Z.wav,172.078000,173.132000
9450,ICLISTENHF1251_20141203T224118.832Z.wav,397.60,56.10,Mn,S,NaN,[9809568],Animalia,Chordata,Mammalia,Cetacea,Balaenopteridae,Megaptera,Humpback whale,Megaptera novaeangliae,Chordata Mammalia Cetacea Balaenopteridae Mega...,audio/ICLISTENHF1251_20141203T224118.832Z.wav,53.278000,54.614000
3039,ICLISTENHF1251_20140204T105224.848Z.wav,371.59,192.39,UN|Mn,NaN,NaN,[9809568],Animalia,Chordata,Mammalia,Cetacea,Balaenopteridae,Megaptera,Humpback whale,Megaptera novaeangliae,Chordata Mammalia Cetacea Balaenopteridae Mega...,audio/ICLISTENHF1251_20140204T105224.848Z.wav,3.574140,5.285170
6370,ICLISTENHF1251_20140903T201409.028Z.wav,398.09,90.24,Mn,NS,NaN,[9809568],Animalia,Chordata,Mammalia,Cetacea,Balaenopteridae,Megaptera,Humpback whale,Megaptera novaeangliae,Chordata Mammalia Cetacea Balaenopteridae Mega...,audio/ICLISTENHF1251_20140903T201409.028Z.wav,49.733840,51.863120
1304,ICLISTENHF1251_20140102T080200.074Z.wav,19777.19,2183.98,DE|Lb|Lo,BP,NaN,"[2440467, 5220069]","Animalia,Animalia","Chordata,Chordata","Mammalia,Mammalia","Cetacea,Cetacea","Delphinidae,Delphinidae","Lissodelphis,Lagenorhynchus","Northern right whale dolphin,Pacific white-sid...","Lissodelphis borealis,Lagenorhynchus obliquidens","Chordata,Chordata Mammalia,Mammalia Cetacea,Ce...",audio/ICLISTENHF1251_20140102T080200.074Z.wav,294.349460,295.189110
3888,ICLISTENHF1251_20140403T003459.297Z.wav,23.36,14.11,Bp,backbeat,NaN,[2440718],Animalia,Chordata,Mammalia,Cetacea,Balaenopteridae,Balaenoptera,Fin whale,Balaenoptera physalus,Chordata Mammalia Cetacea Balaenopteridae Bala...,audio/ICLISTENHF1251_20140403T003459.297Z.wav,190.190110,192.129280
1932,ICLISTENHF1251_20140104T064200.588Z.wav,31999.00,19502.63,DE|Lo,CK,NaN,[5220069],Animalia,Chordata,Mammalia,Cetacea,Delphinidae,Lagenorhynchus,Pacific white-sided dolphin,Lagenorhynchus obliquidens,Chordata Mammalia Cetacea Delphinidae Lagenorh...,audio/ICLISTENHF1251_20140104T064200.588Z.wav,37.832700,38.897330
2258,ICLISTENHF1251_20140201T051212.135Z.wav,11720.90,2357.51,DE|Lb|Lo,BP,NaN,"[2440467, 5220069]","Animalia,Animalia","Chordata,Chordata","Mammalia,Mammalia","Cetacea,Cetacea","Delphinidae,Delphinidae","Lissodelphis,Lagenorhynchus","Northern right whale dolphin,Pacific white-sid...","Lissodelphis borealis,Lagenorhynchus obliquidens","Chordata,Chordata Mammalia,Mammalia Cetacea,Ce...",audio/ICLISTENHF1251_20140201T051212.135Z.wav,109.799090,110.390450
6802,ICLISTENHF1251_20141001T032108.334Z.wav,55.10,10.52,Bm,B,NaN,[2440735],Animalia,Chordata,Mammalia,Cetacea,Balaenopteridae,Balaenoptera,Blue whale,Balaenoptera musculus,Chordata Mammalia Cetacea Balaenopteridae Bala...,audio/ICLISTENHF1251_20141001T032108.334Z.wav,39.277560,61.901140
210,ICLISTENHF1251_20130623T074000.113Z.wav,6276.42,606.07,Oo,BP,BKW,[2440483],Animalia,Chordata,Mammalia,Cetacea,Delphinidae,Orcinus,Killer whale,Orcinus orca,Chordata Mammalia Cetacea Delphinidae Orcinus ...,audio/ICLISTENHF1251_20130623T074000.113Z.wav,232.509050,233.359460
9252,ICLISTENHF1251_20141203T065145.153Z.wav,31.53,15.88,Bp,classic,NaN,[2440718],Animalia,Chordata,Mammalia,Cetacea,Balaenopteridae,Balaenoptera,Fin whale,Balaenoptera physalus,Chordata Mammalia Cetacea Balaenopteridae Bala...,audio/ICLISTENHF1251_20141203T065145.153Z.wav,147.376420,149.163500
1380,ICLISTENHF1251_20140102T123200.121Z.wav,621.30,463.20,Mn,S,NaN,[9809568],Animalia,Chordata,Mammalia,Cetacea,Balaenopteridae,Megaptera,Humpback whale,Megaptera novaeangliae,Chordata Mammalia Cetacea Balaenopteridae Mega...,audio/ICLISTENHF1251_20140102T123200.121Z.wav,240.009000,240.871000
2500,ICLISTENHF1251_20140202T084456.293Z.wav,662.80,454.70,Mn,NaN,NaN,[9809568],Animalia,Chordata,Mammalia,Cetacea,Balaenopteridae,Megaptera,Humpback whale,Megaptera novaeangliae,Chordata Mammalia Cetacea Balaenopteridae Mega...,audio/ICLISTENHF1251_20140202T084456.293Z.wav,205.062000,205.751000
6864,ICLISTENHF1251_20141001T064108.368Z.wav,66.45,10.00,Bm,B,NaN,[2440735],Animalia,Chordata,Mammalia,Cetacea,Balaenopteridae,Balaenoptera,Blue whale,Balaenoptera musculus,Chordata Mammalia Cetacea Balaenopteridae Bala...,audio/ICLISTENHF1251_20141001T064108.368Z.wav,18.859320,39.163500
6999,ICLISTENHF1251_20141001T171347.795Z.wav,6135.25,752.08,Mn,S,NaN,[9809568],Animalia,Chordata,Mammalia,Cetacea,Balaenopteridae,Megaptera,Humpback whale,Megaptera novaeangliae,Chordata Mammalia Cetacea Balaenopteridae Mega...,audio/ICLISTENHF1251_20141001T171347.795Z.wav,3.726240,5.513310
2685,ICLISTENHF1251_20140203T025456.494Z.wav,28.37,13.77,Bp,backbeat,NaN,[2440718],Animalia,Chordata,Mammalia,Cetacea,Balaenopteridae,Balaenoptera,Fin whale,Balaenoptera physalus,Chordata Mammalia Cetacea Balaenopteridae Bala...,audio/ICLISTENHF1251_20140203T025456.494Z.wav,25.931560,27.870720
8918,ICLISTENHF1251_20141202T084144.928Z.wav,502.80,201.10,Mn,S,NaN,[9809568],Animalia,Chordata,Mammalia,Cetacea,Balaenopteridae,Megaptera,Humpback whale,Megaptera novaeangliae,Chordata Mammalia Cetacea Balaenopteridae Mega...,audio/ICLISTENHF1251_20141202T084144.928Z.wav,148.796000,151.434000
8752,ICLISTENHF1251_20141201T220144.815Z.wav,19749.30,9809.30,DE|Lb|Lo,BP,NaN,"[2440467, 5220069]","Animalia,Animalia","Chordata,Chordata","Mammalia,Mammalia","Cetacea,Cetacea","Delphinidae,Delphinidae","Lissodelphis,Lagenorhynchus","Northern right whale dolphin,Pacific white-sid...","Lissodelphis borealis,Lagenorhynchus obliquidens","Chordata,Chordata Mammalia,Mammalia Cetacea,Ce...",audio/ICLISTENHF1251_20141201T220144.815Z.wav,235.711000,235.766000
4450,ICLISTENHF1251_20140601T040134.236Z.wav,680.94,61.71,Mn,NS,NaN,[9809568],Animalia,Chordata,Mammalia,Cetacea,Balaenopteridae,Megaptera,Humpback whale,Megaptera novaeangliae,Chordata Mammalia Cetacea Balaenopteridae Mega...,audio/ICLISTENHF1251_20140601T040134.236Z.wav,4.752840,6.083650
3371,ICLISTENHF1251_20140302T081327.737Z.wav,393.10,192.70,Mn,S,NaN,[9809568],Animalia,Chordata,Mammalia,Cetacea,Balaenopteridae,Megaptera,Humpback whale,Megaptera novaeangliae,Chordata Mammalia Cetacea Balaenopteridae Mega...,audio/ICLISTENHF1251_20140302T081327.737Z.wav,72.115000,73.380000
2350,ICLISTENHF1251_20140201T103212.198Z.wav,14561.54,1618.31,DE|Lb|Lo,BP,NaN,"[2440467, 5220069]","Animalia,Animalia","Chordata,Chordata","Mammalia,Mammalia","Cetacea,Cetacea","Delphinidae,Delphinidae","Lissodelphis,Lagenorhynchus","Northern right whale dolphin,Pacific white-sid...","Lissodelphis borealis,Lagenorhynchus obliquidens","Chordata,Chordata Mammalia,Mammalia Cetacea,Ce...",audio/ICLISTENHF1251_20140201T103212.198Z.wav,113.631540,114.336620
1515,ICLISTENHF1251_20140103T031200.271Z.wav,32.30,20.00,Bp,classic,NaN,[2440718],Animalia,Chordata,Mammalia,Cetacea,Balaenopteridae,Balaenoptera,Fin whale,Balaenoptera physalus,Chordata Mammalia Cetacea Balaenopteridae Bala...,audio/ICLISTENHF1251_20140103T031200.271Z.wav,37.092000,39.238000
938,ICLISTENHF1251_20140101T055159.779Z.wav,41.95,10.00,Bp,classic,NaN,[2440718],Animalia,Chordata,Mammalia,Cetacea,Balaenopteridae,Balaenoptera,Fin whale,Balaenoptera physalus,Chordata Mammalia Cetacea Balaenopteridae Bala...,audio/ICLISTENHF1251_20140101T055159.779Z.wav,235.790350,237.518410
8330,ICLISTENHF1251_20141104T161302.493Z.wav,592.35,414.73,UN|Mn|NN,NaN,NaN,[9809568],Animalia,Chordata,Mammalia,Cetacea,Balaenopteridae,Megaptera,"Humpback whale,Unknown","Megaptera novaeangliae,Unknown",Chordata Mammalia Cetacea Balaenopteridae Mega...,audio/ICLISTENHF1251_20141104T161302.493Z.wav,195.057030,196.730040
737,ICLISTENHF1251_20130812T193120.884Z.wav,19359.29,480.04,Oo,BP,OKW,[2440483],Animalia,Chordata,Mammalia,Cetacea,Delphinidae,Orcinus,Killer whale,Orcinus orca,Chordata Mammalia Cetacea Delphinidae Orcinus ...,audio/ICLISTENHF1251_20130812T193120.884Z.wav,177.439890,179.801680
6517,ICLISTENHF1251_20140904T090409.168Z.wav,2016.03,114.80,Mn,NS,NaN,[9809568],Animalia,Chordata,Mammalia,Cetacea,Balaenopteridae,Megaptera,Humpback whale,Megaptera novaeangliae,Chordata Mammalia Cetacea Balaenopteridae Mega...,audio/ICLISTENHF1251_20140904T090409.168Z.wav,187.262360,188.973380
976,ICLISTENHF1251_20140101T112159.847Z.wav,555.39,356.41,Mn,S,NaN,[9809568],Animalia,Chordata,Mammalia,Cetacea,Balaenopteridae,Megaptera,Humpback whale,Megaptera novaeangliae,Chordata Mammalia Cetacea Balaenopteridae Mega...,audio/ICLISTENHF1251_20140101T112159.847Z.wav,26.674480,28.060950
6789,ICLISTENHF1251_20141001T023108.323Z.wav,59.44,10.52,Bm,B,NaN,[2440735],Animalia,Chordata,Mammalia,Cetacea,Balaenopteridae,Balaenoptera,Blue whale,Balaenoptera musculus,Chordata Mammalia Cetacea Balaenopteridae Bala...,audio/ICLISTENHF1251_20141001T023108.323Z.wav,129.695820,138.707220
5959,ICLISTENHF1251_20140901T155408.453Z.wav,47.70,40.60,Bm,B,NaN,[2440735],Animalia,Chordata,Mammalia,Cetacea,Balaenopteridae,Balaenoptera,Blue whale,Balaenoptera musculus,Chordata Mammalia Cetacea Balaenopteridae Bala...,audio/ICLISTENHF1251_20140901T155408.453Z.wav,37.706000,56.558000
3889,ICLISTENHF1251_20140403T004459.299Z.wav,29.60,16.26,Bp,classic,NaN,[2440718],Animalia,Chordata,Mammalia,Cetacea,Balaenopteridae,Balaenoptera,Fin whale,Balaenoptera physalus,Chordata Mammalia Cetacea Balaenopteridae Bala...,audio/ICLISTENHF1251_20140403T004459.299Z.wav,286.653990,288.136880
1680,ICLISTENHF1251_20140103T140200.397Z.wav,31999.00,20530.33,DE|Lo,CK,NaN,[5220069],Animalia,Chordata,Mammalia,Cetacea,Delphinidae,Lagenorhynchus,Pacific white-sided dolphin,Lagenorhynchus obliquidens,Chordata Mammalia Cetacea Delphinidae Lagenorh...,audio/ICLISTENHF1251_20140103T140200.397Z.wav,27.839920,28.422640
115,ICLISTENHF1251_20130520T190343.707Z.wav,3556.05,846.02,Oo,BP,BKW,[2440483],Animalia,Chordata,Mammalia,Cetacea,Delphinidae,Orcinus,Killer whale,Orcinus orca,Chordata Mammalia Cetacea Delphinidae Orcinus ...,audio/ICLISTENHF1251_20130520T190343.707Z.wav,178.443910,179.728580
8442,ICLISTENHF1251_20141104T234122.697Z.wav,1426.70,124.60,Mn,NS,NaN,[9809568],Animalia,Chordata,Mammalia,Cetacea,Balaenopteridae,Megaptera,Humpback whale,Megaptera novaeangliae,Chordata Mammalia Cetacea Balaenopteridae Mega...,audio/ICLISTENHF1251_20141104T234122.697Z.wav,60.416000,60.885000
1337,ICLISTENHF1251_20140102T094200.094Z.wav,16498.74,5182.60,DE|Lb|Lo,BP,NaN,"[2440467, 5220069]","Animalia,Animalia","Chordata,Chordata","Mammalia,Mammalia","Cetacea,Cetacea","Delphinidae,Delphinidae","Lissodelphis,Lagenorhynchus","Northern right whale dolphin,Pacific white-sid...","Lissodelphis borealis,Lagenorhynchus obliquidens","Chordata,Chordata Mammalia,Mammalia Cetacea,Ce...",audio/ICLISTENHF1251_20140102T094200.094Z.wav,184.752180,185.957800

In [13]:
import pdb
from tqdm.notebook import tqdm

In [14]:
taxonomies = []

for i, row in tqdm(df.iterrows(), total=len(df)):

    ans = row["answer"].split(",")

    tax = {"gbifID": None,
           "kingdom": None,
           "phylum": None,
           "class": None,
           "order": None,
           "family": None,
           "genus": None,
           "taxonomic_name": None
          }
    if len(ans) == 1 and ans[0] == "None":
        taxonomies.append(tax)
        continue
           
    for a in ans:
        if a == "None":
            continue
            
        matching_rows = bc.loc[bc["species_common"].apply(lambda x: a in x)]
        
        if matching_rows.empty:
            continue

        r = matching_rows.iloc[0].to_dict()

        for key in list(tax.keys()):
            if tax[key] is None:
                if key == "gbifID":
                    v = json.loads(r[key])
                    tax[key] = v if isinstance(v, list) else [v]
                else:
                    tax[key] = [r[key]]
            else:
                if key == "gbifID":
                    v = json.loads(r[key])
                    tax[key].extend(v)
                else:
                    tax[key].append(r[key])

    taxonomies.append(tax)

  0%|          | 0/308865 [00:00<?, ?it/s]

In [15]:
len(taxonomies)

308865

In [16]:
taxonomies[1000]

{'gbifID': [2440483],
 'kingdom': ['Animalia'],
 'phylum': ['Chordata'],
 'class': ['Mammalia'],
 'order': ['Cetacea'],
 'family': ['Delphinidae'],
 'genus': ['Orcinus'],
 'taxonomic_name': ['Chordata Mammalia Cetacea Delphinidae Orcinus orca']}

In [17]:
taxonomies = pd.DataFrame(taxonomies)
taxonomies.shape

(308865, 8)

In [18]:
taxonomies.head(3)

  gbifID kingdom phylum class order family genus taxonomic_name
0   None    None   None  None  None   None  None           None
1   None    None   None  None  None   None  None           None
2   None    None   None  None  None   None  None           None

In [19]:
df = pd.concat([df.reset_index(drop=True), taxonomies], axis=1)
df.shape

(308865, 11)

## Add species_scientific

In [20]:
species_scientific = []
for i, row in df.iterrows():
    sci = []
    if row["family"] and len(row["family"]) > 0:
        if len(row["family"]) > 1:        
            pdb.set_trace()
            
        for r in row["taxonomic_name"]:
            s = " ".join(r.split(" ")[-2:])
            s = s.strip()
            sci.append(s)
            
    else:
        sci = None

    species_scientific.append(sci)

In [21]:
df["species_scientific"] = species_scientific

# Add file_name column

In [22]:
from pathlib import Path

In [23]:
df["file_name"] = df["path"].apply(lambda x: Path(x).name)

In [24]:
df["file_name"].head(3)

0    ICLISTENHF1251_20130520T003321.072Z_000.wav
1    ICLISTENHF1251_20130520T003321.072Z_001.wav
2    ICLISTENHF1251_20130520T003321.072Z_002.wav
Name: file_name, dtype: object

# Change 'path' to local_path and remove 'barkley-detection' from it

In [25]:
df.rename(columns={"path": "local_path"}, inplace=True)
df["local_path"] = df["local_path"].apply(lambda x: Path("audio") / Path(x).name)

In [26]:
df["local_path"].head(5)

0    audio/ICLISTENHF1251_20130520T003321.072Z_000.wav
1    audio/ICLISTENHF1251_20130520T003321.072Z_001.wav
2    audio/ICLISTENHF1251_20130520T003321.072Z_002.wav
3    audio/ICLISTENHF1251_20130520T003321.072Z_003.wav
4    audio/ICLISTENHF1251_20130520T003321.072Z_004.wav
Name: local_path, dtype: object

# Rename 'answer' to species_common

In [27]:
df.rename(columns={"answer": "species_common"}, inplace=True)

In [28]:
df["species_common"].dtype

dtype('O')

### Convert it to list[str] instead of comma separated list

In [37]:
df.sample(n=50)

,instruction,local_path,species_common,gbifID,kingdom,phylum,class,order,family,genus,taxonomic_name,species_scientific,file_name
13116,{barkley-detection-common},audio/ICLISTENHF1251_20140102T040200.028Z_018.wav,None,None,None,None,None,None,None,None,None,None,ICLISTENHF1251_20140102T040200.028Z_018.wav
25581,{barkley-detection-common},audio/ICLISTENHF1251_20140103T163200.428Z_034.wav,None,None,None,None,None,None,None,None,None,None,ICLISTENHF1251_20140103T163200.428Z_034.wav
105450,{barkley-detection-common},audio/ICLISTENHF1251_20140403T025459.324Z_017.wav,None,None,None,None,None,None,None,None,None,None,ICLISTENHF1251_20140403T025459.324Z_017.wav
282625,{barkley-detection-common},audio/ICLISTENHF1251_20141201T215144.815Z_015.wav,None,None,None,None,None,None,None,None,None,None,ICLISTENHF1251_20141201T215144.815Z_015.wav
43217,{barkley-detection-common},audio/ICLISTENHF1251_20140201T202456.169Z_029.wav,None,None,None,None,None,None,None,None,None,None,ICLISTENHF1251_20140201T202456.169Z_029.wav
79514,{barkley-detection-common},audio/ICLISTENHF1251_20140302T121327.796Z_041.wav,None,None,None,None,None,None,None,None,None,None,ICLISTENHF1251_20140302T121327.796Z_041.wav
86883,{barkley-detection-common},audio/ICLISTENHF1251_20140304T045328.231Z_035.wav,None,None,None,None,None,None,None,None,None,None,ICLISTENHF1251_20140304T045328.231Z_035.wav
90004,{barkley-detection-common},audio/ICLISTENHF1251_20140304T144328.348Z_029.wav,None,None,None,None,None,None,None,None,None,None,ICLISTENHF1251_20140304T144328.348Z_029.wav
304843,{barkley-detection-common},audio/ICLISTENHF1251_20141204T123118.993Z_049.wav,None,None,None,None,None,None,None,None,None,None,ICLISTENHF1251_20141204T123118.993Z_049.wav
112290,{barkley-detection-common},audio/ICLISTENHF1251_20140404T044459.579Z_013.wav,None,None,None,None,None,None,None,None,None,None,ICLISTENHF1251_20140404T044459.579Z_013.wav
264797,{barkley-detection-common},audio/ICLISTENHF1251_20141103T192254.763Z_005.wav,None,None,None,None,None,None,None,None,None,None,ICLISTENHF1251_20141103T192254.763Z_005.wav
65017,{barkley-detection-common},audio/ICLISTENHF1251_20140204T145224.882Z_058.wav,None,None,None,None,None,None,None,None,None,None,ICLISTENHF1251_20140204T145224.882Z_058.wav
305703,{barkley-detection-common},audio/ICLISTENHF1251_20141204T150105.582Z_024.wav,None,None,None,None,None,None,None,None,None,None,ICLISTENHF1251_20141204T150105.582Z_024.wav
65069,{barkley-detection-common},audio/ICLISTENHF1251_20140204T150224.885Z_051.wav,None,None,None,None,None,None,None,None,None,None,ICLISTENHF1251_20140204T150224.885Z_051.wav
29561,{barkley-detection-common},audio/ICLISTENHF1251_20140104T042200.560Z_002.wav,None,None,None,None,None,None,None,None,None,None,ICLISTENHF1251_20140104T042200.560Z_002.wav
24591,{barkley-detection-common},audio/ICLISTENHF1251_20140103T134200.394Z_047.wav,None,None,None,None,None,None,None,None,None,None,ICLISTENHF1251_20140103T134200.394Z_047.wav
12946,{barkley-detection-common},audio/ICLISTENHF1251_20140102T033200.022Z_025.wav,None,None,None,None,None,None,None,None,None,None,ICLISTENHF1251_20140102T033200.022Z_025.wav
245480,{barkley-detection-common},audio/ICLISTENHF1251_20141003T074130.887Z_040.wav,None,None,None,None,None,None,None,None,None,None,ICLISTENHF1251_20141003T074130.887Z_040.wav
164729,{barkley-detection-common},audio/ICLISTENHF1251_20140703T031216.631Z_001.wav,None,None,None,None,None,None,None,None,None,None,ICLISTENHF1251_20140703T031216.631Z_001.wav
106687,{barkley-detection-common},audio/ICLISTENHF1251_20140403T063459.365Z_015.wav,None,None,None,None,None,None,None,None,None,None,ICLISTENHF1251_20140403T063459.365Z_015.wav
191481,{barkley-detection-common},audio/ICLISTENHF1251_20140803T110424.065Z_026.wav,None,None,None,None,None,None,None,None,None,None,ICLISTENHF1251_20140803T110424.065Z_026.wav
79902,{barkley-detection-common},audio/ICLISTENHF1251_20140302T132327.813Z_016.wav,None,None,None,None,None,None,None,None,None,None,ICLISTENHF1251_20140302T132327.813Z_016.wav
118785,{barkley-detection-common},audio/ICLISTENHF1251_20140501T102349.486Z_018.wav,None,None,None,None,None,None,None,None,None,None,ICLISTENHF1251_20140501T102349.486Z_018.wav
145279,{barkley-detection-common},audio/ICLISTENHF1251_20140602T090123.917Z_021.wav,None,None,None,None,None,None,None,None,None,None,ICLISTENHF1251_20140602T090123.917Z_021.wav
176459,{barkley-detection-common},audio/ICLISTENHF1251_20140704T150257.467Z_049.wav,None,None,None,None,None,None,None,None,None,None,ICLISTENHF1251_20140704T150257.467Z_049.wav
255939,{barkley-detection-common},audio/ICLISTENHF1251_20141004T212107.295Z_056.wav,None,None,None,None,None,None,None,None,None,None,ICLISTENHF1251_20141004T212107.295Z_056.wav
186505,{barkley-detection-common},audio/ICLISTENHF1251_20140802T092028.654Z_006.wav,None,None,None,None,None,None,None,None,None,None,ICLISTENHF1251_20140802T092028.654Z_006.wav
254363,{barkley-detection-common},audio/ICLISTENHF1251_20141004T120246.187Z_014.wav,None,None,None,None,None,None,None,None,None,None,ICLISTENHF1251_20141004T120246.187Z_014.wav
170994,{barkley-detection-common},audio/ICLISTENHF1251_20140703T234257.299Z_012.wav,None,None,None,None,None,None,None,None,None,None,ICLISTENHF1251_20140703T234257.299Z_012.wav
56789,{barkley-detection-common},audio/ICLISTENHF1251_20140203T143101.585Z_031.wav,None,None,None,None,None,None,None,None,None,None,ICLISTENHF1251_20140203T143101.585Z_031.wav
296027,{barkley-detection-common},audio/ICLISTENHF1251_20141203T114122.092Z_024.wav,None,None,None,None,None,None,None,None,None,None,ICLISTENHF1251_20141203T114122.092Z_024.wav
63644,{barkley-detection-common},audio/ICLISTENHF1251_20140204T100224.838Z_042.wav,None,None,None,None,None,None,None,None,None,None,ICLISTENHF1251_20140204T100224.838Z_042.wav
36535,{barkley-detection-common},audio/ICLISTENHF1251_20140104T211150.175Z_014.wav,None,None,None,None,None,None,None,None,None,None,ICLISTENHF1251_20140104T211150.175Z_014.wav
146868,{barkley-detection-common},audio/ICLISTENHF1251_20140603T064124.154Z_017.wav,None,None,None,None,None,None,None,None,None,None,ICLISTENHF1251_20140603T064124.154Z_017.wav
183144,{barkley-detection-common},audio/ICLISTENHF1251_20140801T170029.293Z_008.wav,None,None,None,None,None,None,None,None,None,None,ICLISTENHF1251_20140801T170029.293Z_008.wav
39832,{barkley-detection-common},audio/ICLISTENHF1251_20140201T063212.151Z_007.wav,None,None,None,None,None,None,None,None,None,None,ICLISTENHF1251_20140201T063212.151Z_007.wav
190886,{barkley-detection-common},audio/ICLISTENHF1251_20140803T091424.045Z_021.wav,None,None,None,None,None,None,None,None,None,None,ICLISTENHF1251_20140803T091424.045Z_021.wav
289218,{barkley-detection-common},audio/ICLISTENHF1251_20141202T163145.009Z_000.wav,None,None,None,None,None,None,None,None,None,None,ICLISTENHF1251_20141202T163145.009Z_000.wav
256724,{barkley-detection-common},audio/ICLISTENHF1251_20141102T202458.330Z_015.wav,None,None,None,None,None,None,None,None,None,None,ICLISTENHF1251_20141102T202458.330Z_015.wav
308196,{barkley-detection-common},audio/ICLISTENHF1251_20141204T220132.164Z_039.wav,None,None,None,None,None,None,None,None,None,None,ICLISTENHF1251_20141204T220132.164Z_039.wav
201504,{barkley-detection-common},audio/ICLISTENHF1251_20140901T095408.390Z_019.wav,None,None,None,None,None,None,None,None,None,None,ICLISTENHF1251_20140901T095408.390Z_019.wav
53320,{barkley-detection-common},audio/ICLISTENHF1251_20140203T041456.514Z_043.wav,None,None,None,None,None,None,None,None,None,None,ICLISTENHF1251_20140203T041456.514Z_043.wav
263166,{barkley-detection-common},audio/ICLISTENHF1251_20141103T143455.336Z_026.wav,None,None,None,None,None,None,None,None,None,None,ICLISTENHF1251_20141103T143455.336Z_026.wav
196511,{barkley-detection-common},audio/ICLISTENHF1251_20140804T114424.338Z_041.wav,None,None,None,None,None,None,None,None,None,None,ICLISTENHF1251_20140804T114424.338Z_041.wav
244921,{barkley-detection-common},audio/ICLISTENHF1251_20141003T061130.869Z_012.wav,Pacific white-sided dolphin,[5220069],[Animalia],[Chordata],[Mammalia],[Cetacea],[Delphinidae],[Lagenorhynchus],[Chordata Mammalia Cetacea Delphinidae Lagenor...,[Lagenorhynchus obliquidens],ICLISTENHF1251_20141003T061130.869Z_012.wav
170778,{barkley-detection-common},audio/ICLISTENHF1251_20140703T230257.292Z_032.wav,None,None,None,None,None,None,None,None,None,None,ICLISTENHF1251_20140703T230257.292Z_032.wav
231613,{barkley-detection-common},audio/ICLISTENHF1251_20141001T153322.088Z_038.wav,None,None,None,None,None,None,None,None,None,None,ICLISTENHF1251_20141001T153322.088Z_038.wav
11688,{barkley-detection-common},audio/ICLISTENHF1251_20140101T234159.969Z_006.wav,None,None,None,None,None,None,None,None,None,None,ICLISTENHF1251_20140101T234159.969Z_006.wav
216386,{barkley-detection-common},audio/ICLISTENHF1251_20140903T144408.967Z_033.wav,None,None,None,None,None,None,None,None,None,None,ICLISTENHF1251_20140903T144408.967Z_033.wav
126095,{barkley-detection-common},audio/ICLISTENHF1251_20140502T202349.785Z_012.wav,None,None,None,None,None,None,None,None,None,None,ICLISTENHF1251_20140502T202349.785Z_012.wav

# Save

In [30]:
df.columns

Index(['instruction', 'local_path', 'species_common', 'gbifID', 'kingdom',
       'phylum', 'class', 'order', 'family', 'genus', 'taxonomic_name',
       'species_scientific', 'file_name'],
      dtype='object')

In [31]:
df.to_csv("gs://esp-ml-datasets/barkley_canyon_detection/v0.1.0/raw/barkley_canyon_detection_gbif.csv", index=False, storage_options={"project": "okapi-274503"})

In [33]:
df.to_json("gs://esp-ml-datasets/barkley_canyon_detection/v0.1.0/raw/barkley_canyon_detection_gbif.jsonl", index=False, orient="records", lines=True, storage_options={"project": "okapi-274503"})

OverflowError: Maximum recursion level reached