In [1]:
import pandas as pd
import numpy as np
from io import StringIO

In [2]:
import csv

In [3]:
data = []
with open("/home/gagan/open_audio_datasets/0031244-250525065834625/occurrence.txt", "r") as f:
    for line in f.readlines():
        data.append(line.strip())

In [4]:
len(data)

795539

In [5]:


df = pd.read_csv('/home/gagan/open_audio_datasets/0031244-250525065834625/occurrence.txt', 
                 sep='\t', 
                 engine='python',  # More flexible parser
                 on_bad_lines='skip',
                 quoting=csv.QUOTE_NONE)

In [6]:
df.shape

(795538, 223)

In [7]:
df.head(3)

,gbifID,accessRights,bibliographicCitation,language,license,modified,publisher,references,rightsHolder,type,...,publishedByGbifRegion,level0Gid,level0Name,level1Gid,level1Name,level2Gid,level2Name,level3Gid,level3Name,iucnRedListCategory
0,2243612868,NaN,NaN,NaN,CC_BY_NC_4_0,NaN,Xeno-canto Foundation for Nature Sounds,https://data.biodiversitydata.nl/xeno-canto/ob...,Bob Planqué,NaN,...,EUROPE,ECU,Ecuador,ECU.3_1,Cañar,ECU.3.1_1,Azogues,ECU.3.1.6_1,Pindilig,NaN
1,4062431942,NaN,NaN,NaN,CC_BY_NC_4_0,NaN,Xeno-canto Foundation for Nature Sounds,https://data.biodiversitydata.nl/xeno-canto/ob...,david m,NaN,...,EUROPE,GBR,United Kingdom,GBR.1_1,England,GBR.1.63_1,North Yorkshire,GBR.1.63.5_1,Ryedale,NaN
2,2243864926,NaN,NaN,NaN,CC_BY_NC_4_0,NaN,Xeno-canto Foundation for Nature Sounds,https://data.biodiversitydata.nl/xeno-canto/ob...,Bob Planqué,NaN,...,EUROPE,PER,Peru,PER.18_1,Madre de Dios,PER.18.3_1,Tambopata,PER.18.3.4_1,Tambopata,LC

In [8]:
cols = list(df.columns)

In [ ]:
cols

In [39]:
"identifier" in cols

False

In [ ]:
cols

In [6]:
multimedia = pd.read_csv("/home/gagan/open_audio_datasets/0031244-250525065834625/multimedia.txt",
                         sep='\t', 
                     engine='python',  # More flexible parser
                     on_bad_lines='skip',
                     quoting=csv.QUOTE_NONE)

In [7]:
multimedia.shape

(2386614, 15)

In [8]:
multimedia.head(3)

,gbifID,type,format,identifier,references,title,description,source,audience,created,creator,contributor,publisher,license,rightsHolder
0,2243612868,StillImage,image/png,https://xeno-canto.org/sounds/uploaded/OH38YHK...,NaN,NaN,Oscillogram of the first ten seconds of the so...,NaN,NaN,NaN,Stichting Xeno-canto voor Natuurgeluiden,NaN,NaN,http://creativecommons.org/licenses/by-nc-sa/3.0/,Stichting Xeno-canto voor Natuurgeluiden
1,2243612868,Sound,audio/mpeg,https://xeno-canto.org/sounds/uploaded/OH38YHK...,NaN,NaN,24 s,NaN,NaN,NaN,Bob Planqué,NaN,NaN,http://creativecommons.org/licenses/by-nc-sa/3.0/,Bob Planqué
2,2243612868,StillImage,image/png,https://xeno-canto.org/sounds/uploaded/OH38YHK...,NaN,NaN,Spectrogram of the first ten seconds of the so...,NaN,NaN,NaN,Stichting Xeno-canto voor Natuurgeluiden,NaN,NaN,http://creativecommons.org/licenses/by-nc-sa/3.0/,Stichting Xeno-canto voor Natuurgeluiden

In [9]:
audio = multimedia[multimedia["type"] == "Sound"]
audio.shape

(795537, 15)

In [19]:
audio.sample(10)

,gbifID,type,format,identifier,references,title,description,source,audience,created,creator,contributor,publisher,license,rightsHolder
986038,2243878091,Sound,audio/mpeg,https://xeno-canto.org/sounds/uploaded/RGSEIIJ...,NaN,NaN,80 s,NaN,NaN,NaN,Bram Piot,NaN,NaN,http://creativecommons.org/licenses/by-nc-nd/2.5/,Bram Piot
1866953,2243841939,Sound,audio/mpeg,https://xeno-canto.org/sounds/uploaded/CCUCXWC...,NaN,NaN,15 s,NaN,NaN,NaN,nick talbot,NaN,NaN,http://creativecommons.org/licenses/by-nc-sa/4.0/,nick talbot
1018826,2848587894,Sound,audio/mpeg,https://xeno-canto.org/sounds/uploaded/XIBLXHR...,NaN,NaN,75 s,NaN,NaN,NaN,Uku Paal,NaN,NaN,http://creativecommons.org/licenses/by-nc-sa/4.0/,Uku Paal
81750,3353664460,Sound,audio/mpeg,https://xeno-canto.org/sounds/uploaded/RFTXRYB...,NaN,NaN,76 s,NaN,NaN,NaN,Paul Marvin,NaN,NaN,http://creativecommons.org/licenses/by-nc-sa/4.0/,Paul Marvin
682761,2609680816,Sound,audio/mpeg,https://xeno-canto.org/sounds/uploaded/XMFDPAC...,NaN,NaN,56 s,NaN,NaN,NaN,Mauricio Álvarez-Rebolledo,NaN,NaN,http://creativecommons.org/licenses/by-nc-sa/4.0/,Mauricio Álvarez-Rebolledo
2195979,2243643797,Sound,audio/mpeg,https://xeno-canto.org/sounds/uploaded/OOECIWC...,NaN,NaN,27 s,NaN,NaN,NaN,Peter Boesman,NaN,NaN,http://creativecommons.org/licenses/by-nc-nd/4.0/,Peter Boesman
1882650,3994959582,Sound,audio/mpeg,https://xeno-canto.org/sounds/uploaded/CCOLFGG...,NaN,NaN,22 s,NaN,NaN,NaN,Allistair Fresse,NaN,NaN,http://creativecommons.org/licenses/by-nc-sa/4.0/,Allistair Fresse
1412009,3051588583,Sound,audio/mpeg,https://xeno-canto.org/sounds/uploaded/OXOBWLV...,NaN,NaN,6 s,NaN,NaN,NaN,Samuel Levy,NaN,NaN,http://creativecommons.org/licenses/by-nc-sa/4.0/,Samuel Levy
1403153,2848602777,Sound,audio/mpeg,https://xeno-canto.org/sounds/uploaded/KDNLNVN...,NaN,NaN,8 s,NaN,NaN,NaN,Martin Sutherland,NaN,NaN,http://creativecommons.org/licenses/by-nc-sa/4.0/,Martin Sutherland
1393872,3353664508,Sound,audio/mpeg,https://xeno-canto.org/sounds/uploaded/PAEQEUH...,NaN,NaN,51 s,NaN,NaN,NaN,Irish Wildlife Sounds,NaN,NaN,http://creativecommons.org/licenses/by-nc-sa/4.0/,Irish Wildlife Sounds

In [40]:
audio.identifier.sample(3).to_dict()

{222036: 'https://xeno-canto.org/sounds/uploaded/KZYUWIRZVH/XC828149-WARBLER_Tennessee-Rock-Bridge-Tr-300m-DBNF-051323-0959.wav',
 2067714: 'https://xeno-canto.org/sounds/uploaded/DREKKBLICT/XC340101-Cettis%20Meijendel%2025102016%20nr1.mp3',
 499495: 'https://xeno-canto.org/sounds/uploaded/BTOFEKXFGW/XC198659-T09.mp3'}

## Duplicates ?

In [38]:
audio = audio.drop_duplicates(subset=["gbifID", "identifier"])
audio.shape

(795537, 15)

# Xeno-canto info from foundation-model-data

In [10]:
xc = pd.read_csv("gs://foundation-model-data/xeno-canto/xeno_canto_2025_v1.csv")

In [11]:
xc.shape

(590009, 22)

In [12]:
xc.columns

Index(['dataset', 'location', 'caption', 'caption2', 'species',
       'scientific_name', 'description', 'url', 'path', 'associatedMedia',
       'behavior', 'sex', 'lifeStage', 'rightsHolder', 'license', 'fieldNotes',
       'Associated Taxa', 'longitudeDecimal', 'latitudeDecimal', 'eventDate',
       'eventTime', 'multimedia_license'],
      dtype='object')

In [13]:
xc.head(3)

,dataset,location,caption,caption2,species,scientific_name,description,url,path,associatedMedia,...,lifeStage,rightsHolder,license,fieldNotes,Associated Taxa,longitudeDecimal,latitudeDecimal,eventDate,eventTime,multimedia_license
0,xeno-canto,audio/xeno-canto/Sickle-bearing Bush-cricket/X...,"Calling song, and female song of a sickle-bear...","Calling song, and female song of a sickle-bear...",Sickle-bearing Bush-cricket,Phaneroptera falcata,original filename: P_falcata_2019_017a M1 W7+ ...,https://xeno-canto.org/sounds/uploaded/KWCPMUX...,audios/xeno-canto/Sickle-bearing Bush-cricket/...,https://xeno-canto.org/sounds/uploaded/KWCPMUX...,...,adult,NaN,NaN,original filename: P_falcata_2019_017a M1 W7+ ...,NaN,11.6166,52.3170,2019-07-26,19:30,CC BY-SA 4.0
1,xeno-canto,audio/xeno-canto/Identity unknown/XC909360-Mix...,Calling song of a identity unknown sex: male. ...,Calling song of a identity unknown sex: male. ...,Identity unknown,Mystery mystery,"This is an undescribed species, potentially wi...",https://xeno-canto.org/sounds/uploaded/PLNKGHY...,audios/xeno-canto/Identity unknown/XC909360-Mi...,https://xeno-canto.org/sounds/uploaded/PLNKGHY...,...,adult,NaN,NaN,"This is an undescribed species, potentially wi...",NaN,20.4866,40.0640,2021-08-26,17:02,CC BY-NC-SA 4.0
2,xeno-canto,audio/xeno-canto/Identity unknown/XC909730-Cic...,Uncertain of a identity unknown,Uncertain of a identity unknown,Identity unknown,Mystery mystery,Cicada; animal seen:no; playback used:no,https://xeno-canto.org/sounds/uploaded/UWHBFUY...,audios/xeno-canto/Identity unknown/XC909730-Ci...,https://xeno-canto.org/sounds/uploaded/UWHBFUY...,...,NaN,NaN,NaN,Cicada; animal seen:no; playback used:no,NaN,-86.2685,32.0373,2019-09-22,14:10,CC BY-NC-SA 4.0

In [14]:
xc.sample(10).location.to_dict()

{181673: 'audio/xeno-canto/Goldcrest/XC702824-191022_04%20Goldcrest%20D%200845%20MR%20XC.mp3',
 232401: 'audio/xeno-canto/Common Grasshopper Warbler/XC637982-For_macchiettato.mp3',
 50139: 'audio/xeno-canto/Chukar Partridge/XC905039-ALECHU_chant_240508_2_Cr%C3%A8te.mp3',
 107360: 'audio/xeno-canto/Mourning Warbler/XC802606-MOWA-60-ms-5-9-kHz-8-ms-hs-Sept-3%2C-2022-0112.wav',
 413638: 'audio/xeno-canto/Common Iora/XC397743-Aegithina%20tiphia%20call1.mp3',
 416054: 'audio/xeno-canto/Black-capped Chickadee/XC394059-BCCH%20and%20mocker%20mill%20creek%20xeno.mp3',
 447443: "audio/xeno-canto/Cetti's Warbler/XC347208-681_cetcet_laulu2_Korsika_2011-04-01.mp3",
 149621: 'audio/xeno-canto/Common Chaffinch/XC745685-T979_1.mp3',
 60582: 'audio/xeno-canto/White-crowned Sparrow/XC942539-WCSP_2024-10-22_Ralph_Dean_Recreation_Park_Luray_VA_0851%282%29.wav',
 287516: 'audio/xeno-canto/European Nightjar/XC567282-European%20Nightjar%20Flight%20Calls%20Bishops%20Wood%200326am%2004062020.mp3'}

In [15]:
sorted(xc.location.tolist()) == sorted(xc.path.tolist())

False

# What needs to be downloaded?

In [16]:
already_there = audio["identifier"].isin(xc["url"])
already_there

1           True
4          False
6           True
9           True
14          True
           ...
2386601     True
2386603     True
2386606     True
2386608     True
2386613     True
Name: identifier, Length: 795537, dtype: bool

In [17]:
to_download = audio["identifier"].iloc[np.where(already_there == False)[0]]
to_download.shape

(223942,)

In [18]:
to_download.to_csv("./xc_to_download.csv", index=False)

In [11]:
223942 * 3 / (60 * 60 * 24)

7.775763888888889