# Preparing barkley_canyon

In [1]:
import pandas as pd

In [97]:
!uv pip install ipywidgets

Audited 1 package in 12ms

# Read original csv

In [22]:
orig = pd.read_csv("gs://foundation-model-data/data/barkley_canyon/BarkleyCanyonAnnotations_Public_Final.csv")
orig.shape

(12763, 22)

In [23]:
orig.columns

Index(['Soundfile', 'Left time (sec)', 'Right time (sec)', 'Top freq (Hz)',
       'Bottom freq (Hz)', 'Species', 'Call Type', 'Ecotype', 'Unnamed: 8',
       'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12',
       'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16',
       'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20',
       'Unnamed: 21'],
      dtype='object')

In [33]:
orig["Call Type"].isnull().sum()

np.int64(3825)

In [50]:
orig = orig.drop(labels=['Unnamed: 8',
       'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12',
       'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16',
       'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20',
       'Unnamed: 21'], axis=1)
orig.shape

(12763, 8)

In [56]:
orig.columns

Index(['Soundfile', 'Left time (sec)', 'Right time (sec)', 'Top freq (Hz)',
       'Bottom freq (Hz)', 'Species', 'Call Type', 'Ecotype'],
      dtype='object')

In [ ]:
orig.sh

In [31]:
orig["Soundfile"].unique().shape

(5254,)

In [52]:
orig["Species"].unique()

array(['Oo', 'Mn', 'BA|Bp', 'BA', 'Bp', 'MY', 'UN|BA', 'UN|DE|Mn',
       'MY|Mn', 'UN|MY|NN', 'UN|MY', 'OD', 'DE|Lo', 'DE|Lb|Lo', 'UN|Mn',
       'DE', 'UN', 'UN|Mn|MY', 'DE|Gg', 'UN|Mn|NN', 'DE|Gg|Lo',
       'DE|Gg|Lb|Lo', 'UN|DE|Lo', 'UN|BA|Bp', 'UN|DE', 'UN|Bp',
       'CE|Mn|Oo', 'CE|Mn', 'MY|Bm', 'MY|Bm|Bp', 'UN|Bm', 'CE|DE',
       'UN|NN|OD', 'NN', 'UN|FI|Mn', 'UN|FI|Mn|NN', 'CE|DE|Mn', 'UN|CE',
       'UN|DE|Oo', 'UN|Mn|Oo', 'UN|Oo', 'DE|Oo', 'UN|NN|OD|Pm', 'UN|Pm',
       'Pm', 'UN|OD|Pm', 'UN|OD', 'UN|Pm|NN', 'UN|NN|Pm', 'UN|DE|NN|OD',
       'Bm', 'UN|NN', 'MY|Er', 'OD|Pm', 'UN|FI', 'UN|DE|OD', 'OD|OOD|Pm',
       'OD|Oo', 'UN|FI|NN|OD', 'UN|DE|NN', 'MY|Ej|Mn', 'MY|Mn|Ej',
       'BA|Bp|Bb', 'Gg', 'UN|Bp|NN', 'UN|FI|NN', 'UN|Ej|NN',
       'UN|BA|FI|NN', 'UN|DE|Mn|NN', 'MY|Er|Mn', 'UN|Er|Mn|NN', 'CE',
       'UN|DE|Gg', 'UN|BA|Bb|Bp', 'UN|Mn|NN|OD', 'AN|Mn', 'DE|Lb|LOD|Oo',
       'AN', 'CE|Mn|DE', 'UN|Mn|OD', 'CE|DE|OD', 'Lo', 'UN|Er|FI',
       'UN|BA|PI', 'UN|BA|NN', 'UN|Er|FI|Mn', 'UN|BA|Er|Mn',
       'UN|BA|FI|PI', 'AN|MY', 'UN|NN|Mn', 'UN||Mn|NN', 'UN|Bm|MY',
       'MY|Ej|Er|Mn', 'UN|FI|MY|NN', 'MY|BBA|Bp|Ej', 'UN|Er|Mn',
       'UN|Bm|Bp', 'UN|Bm|NN', 'MY|BBA|Bp', 'UN|Er', 'CE|DE|OOD|Mn',
       'AN|DE|PI|Mn', 'AN|MY|FI', 'UN|BA|FI', 'DE|Lb', 'DE|Lb|Lo|Oo',
       'UN|DE|Mn|MY', 'CE|Oo', 'UN|BA|FI|OD'], dtype=object)

In [143]:
# got this from foundation-model-data
# https://github.com/earthspecies/foundation-model-data/blob/main/scripts/convert_barkley_canyon.py

HIGH_LEVEL_TAXA = {
    "BA", "DE", "MY", "OD", "CE", "PI", "MA", "FI", "AN", "NN"
}

species_map_scientific = {
    "Bm": "Balaenoptera musculus",
    "Bp": "Balaenoptera physalus",
    "Bb": "Balaenoptera borealis",
    "Mn": "Megaptera novaeangliae",
    "Er": "Eschrichtius robustus",
    "Ej": "Eubalaena japonica",
    "Pm": "Physeter macrocephalus",
    "Oo": "Orcinus orca",
    "Gg": "Grampus griseus",
    "Lo": "Lagenorhynchus obliquidens",
    "Lb": "Lissodelphis borealis",
    "BA": "Balaenoptera (Genus)",
    "DE": "Delphinidae (Family of dolphins)",
    "MY": "Mysticeti (Baleen whales)",
    "OD": "Odontoceti (Toothed whales)",
    "CE": "Cetacea (Whales, dolphins, porpoises)",
    "PI": "Pinnipedia (Seals, sea lions, walruses)",
    "MA": "Mammalia (Mammals)",
    "FI": "Fish",
    "AN": "Animalia (Animals)",
    "UN": "Unknown"
}

species_map_common = {
    "Bm": "Blue whale",
    "Bp": "Fin whale",
    "Bb": "Sei whale",
    "Mn": "Humpback whale",
    "Er": "Gray whale",
    "Ej": "North Pacific right whale",
    "Pm": "Sperm whale",
    "Oo": "Killer whale",
    "Gg": "Risso’s dolphin",
    "Lo": "Pacific white-sided dolphin",
    "Lb": "Northern right whale dolphin",
    "BA": "Balaenoptera",
    "DE": "Delphinidae",
    "MY": "Baleen whales",
    "OD": "Toothed whales",
    "CE": "Cetaceans",
    "PI": "Pinnipeds",
    "MA": "Mammals",
    "FI": "Fish",
    "AN": "Animals",
    "UN": "Unknown"
}

call_type_map = {
    "CK": "Click",
    "BZ": "Buzz",
    "W": "Whistle",
    "BP": "Burst-Pulse",
    "S": "Humpback song",
    "NS": "Humpback non-song",
    "A": "Blue whale A call",
    "B": "Blue whale B call",
    "C": "Blue whale C call",
    "D": "Blue whale D call",
    "40 Hz": "Fin whale 40 Hz call",
    "classic": "Fin whale 20Hz call (classic)",
    "backbeat": "Fin whale 20Hz call (backbeat)",
    # "O": "Other call type"
}

In [15]:
df = pd.read_json("gs://foundation-model-data/data/barkley_canyon/barkley_detection_common.jsonl",
                  orient="records", lines=True)

In [20]:
df["path"].iloc[0]

'audio/barkley-detection/ICLISTENHF1251_20130520T003321.072Z_000.wav'

In [21]:
df["answer"].unique()

array(['None', 'Killer whale', 'Humpback whale', 'Fin whale',
       'Fin whale, Humpback whale', 'Sperm whale',
       'Fin whale, Sperm whale', 'Blue whale', 'Fin whale, Killer whale',
       'Risso’s dolphin', 'Humpback whale, Sperm whale',
       'Risso’s dolphin, Sperm whale', 'Humpback whale, Risso’s dolphin',
       'Pacific white-sided dolphin', 'Humpback whale, Killer whale',
       'Humpback whale, Pacific white-sided dolphin',
       'Killer whale, Sperm whale', 'Blue whale, Sperm whale',
       'Blue whale, Humpback whale', 'Blue whale, Risso’s dolphin',
       'Blue whale, Fin whale', 'Blue whale, Fin whale, Humpback whale',
       'Fin whale, Pacific white-sided dolphin',
       'Blue whale, Pacific white-sided dolphin',
       'Fin whale, Humpback whale, Pacific white-sided dolphin'],
      dtype=object)

In [54]:
import duckdb

In [58]:
conn = duckdb.connect("/Users/gagan/esp-ml-datasets/gbif_taxonomy.db")

In [102]:
def get_taxonomy(sci_name: str) -> dict[str, str]:
    query = f"""SELECT TaxonID, Kingdom, Phylum, "Class", "Order", Family, Genus
    FROM gbif WHERE ScientificName = '{sci_name}';"""
    out = conn.sql(query).fetchall()
    if len(out) == 0:
        return None
    out = out[0]
    return {"gbifID": out[0],
            "kingdom": out[1],
            "phylum": out[2],
            "class": out[3],
            "order": out[4],
            "family": out[5],
            "genus": out[6],
           }

In [91]:
get_taxonomy(species_map_scientific["Bm"])

SELECT TaxonID, Kingdom, Phylum, "Class", "Order", Family, Genus
    FROM gbif WHERE ScientificName = 'Balaenoptera musculus';

{'gbifID': 2440735,
 'kingdom': 'Animalia',
 'phylum': 'Chordata',
 'class': 'Mammalia',
 'order': 'Cetacea',
 'family': 'Balaenopteridae',
 'genus': 'Balaenoptera'}

# Loop over barkley canyon dataset and add taxonomy

In [121]:
from tqdm.notebook import tqdm

In [144]:
taxonomy = {"gbifID": [],
            "kingdom": [],
            "phylum": [],
            "class": [],
            "order": [],
            "family": [],
            "genus": [],
            "species_common": [],
            "species_scientific": [],
            "taxonomic_name": []}

for i, row in tqdm(orig.iterrows(), total=len(orig)):
    detected_species = row["Species"].split("|")

    gbifID = []
    kingdom = []
    phylum = []
    _class = []
    order = []
    family = []
    genus = []
    species_common = []
    species_scientific = []
    taxonomic_name = []
    
    for d in detected_species:
        
        if d in HIGH_LEVEL_TAXA:
            species_sci = "Unknown"
            species_comm = "Unknown"
            
            species_common.append(species_comm)
            species_scientific.append(species_sci)
            continue
            
        else:
            species_sci = species_map_scientific.get(d, "Unknown")
            species_comm = species_map_common.get(d, "Unknown")
        
            species_common.append(species_comm)
            species_scientific.append(species_sci)
        
        tax = get_taxonomy(species_sci)
        if tax is None:
            continue
        taxname = tax["phylum"] + " "  + tax["class"] + " " + tax["order"] + " " + tax["family"] + " " + tax["genus"]
        
        gbifID.append(tax["gbifID"])
        kingdom.append(tax["kingdom"])
        phylum.append(tax["phylum"])
        _class.append(tax["class"])
        order.append(tax["order"])
        family.append(tax["family"])
        genus.append(tax["genus"])
        taxonomic_name.append(taxname)

    taxonomy["gbifID"].append(gbifID or pd.NA)
    taxonomy["kingdom"].append(",".join(kingdom) or pd.NA)
    taxonomy["phylum"].append(",".join(phylum) or pd.NA)
    taxonomy["class"].append(",".join(_class) or pd.NA)
    taxonomy["order"].append(",".join(order) or pd.NA)
    taxonomy["family"].append(",".join(family) or pd.NA)
    taxonomy["genus"].append(",".join(genus) or pd.NA)
    taxonomy["species_common"].append(",".join(species_common))
    taxonomy["species_scientific"].append(",".join(species_scientific))
    taxonomy["taxonomic_name"].append(",".join(taxonomic_name) or pd.NA)

  0%|          | 0/12763 [00:00<?, ?it/s]

In [145]:
len(taxonomy["genus"])

12763

In [146]:
taxonomy = pd.DataFrame(taxonomy)

In [150]:
taxonomy.sample(n=10, replace=True)

,gbifID,kingdom,phylum,class,order,family,genus,species_common,species_scientific,taxonomic_name
10506,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,"Unknown,Unknown","Unknown,Unknown",<NA>
9606,[5220069],Animalia,Chordata,Mammalia,Cetacea,Delphinidae,Lagenorhynchus,Pacific white-sided dolphin,Lagenorhynchus obliquidens,Chordata Mammalia Cetacea Delphinidae Lagenorh...
2502,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Unknown,Unknown,<NA>
6375,[8123917],Animalia,Chordata,Mammalia,Cetacea,Physeteridae,Physeter,Sperm whale,Physeter macrocephalus,Chordata Mammalia Cetacea Physeteridae Physeter
1647,[5220069],Animalia,Chordata,Mammalia,Cetacea,Delphinidae,Lagenorhynchus,"Unknown,Pacific white-sided dolphin","Unknown,Lagenorhynchus obliquidens",Chordata Mammalia Cetacea Delphinidae Lagenorh...
9455,[9809568],Animalia,Chordata,Mammalia,Cetacea,Balaenopteridae,Megaptera,Humpback whale,Megaptera novaeangliae,Chordata Mammalia Cetacea Balaenopteridae Mega...
2145,"[2440467, 5220069]","Animalia,Animalia","Chordata,Chordata","Mammalia,Mammalia","Cetacea,Cetacea","Delphinidae,Delphinidae","Lissodelphis,Lagenorhynchus","Unknown,Northern right whale dolphin,Pacific w...","Unknown,Lissodelphis borealis,Lagenorhynchus o...",Chordata Mammalia Cetacea Delphinidae Lissodel...
8484,"[2440467, 5220069]","Animalia,Animalia","Chordata,Chordata","Mammalia,Mammalia","Cetacea,Cetacea","Delphinidae,Delphinidae","Lissodelphis,Lagenorhynchus","Unknown,Northern right whale dolphin,Pacific w...","Unknown,Lissodelphis borealis,Lagenorhynchus o...",Chordata Mammalia Cetacea Delphinidae Lissodel...
11711,[9809568],Animalia,Chordata,Mammalia,Cetacea,Balaenopteridae,Megaptera,Humpback whale,Megaptera novaeangliae,Chordata Mammalia Cetacea Balaenopteridae Mega...
1038,[9809568],Animalia,Chordata,Mammalia,Cetacea,Balaenopteridae,Megaptera,Humpback whale,Megaptera novaeangliae,Chordata Mammalia Cetacea Balaenopteridae Mega...

In [138]:
taxonomy["taxonomic_name"].iloc[-2]

'Chordata Mammalia Cetacea Balaenopteridae Balaenoptera'

In [151]:
orig_tax = pd.concat([orig, taxonomy], axis=1)
orig_tax.shape

(12763, 18)

# Export csvs

In [152]:
orig_tax.to_csv("barkley_canyon_annotations.csv", index=False)

In [153]:
orig_tax.columns

Index(['Soundfile', 'Left time (sec)', 'Right time (sec)', 'Top freq (Hz)',
       'Bottom freq (Hz)', 'Species', 'Call Type', 'Ecotype', 'gbifID',
       'kingdom', 'phylum', 'class', 'order', 'family', 'genus',
       'species_common', 'species_scientific', 'taxonomic_name'],
      dtype='object')

## Also save a version where rows with no species detected are removed

In [156]:
orig_tax_non_null = orig_tax.dropna(how="any", axis=0, subset="gbifID")

In [157]:
orig_tax_non_null.shape

(9782, 18)

In [159]:
orig_tax_non_null.to_csv("barkley_canyon_annotations_non_null_gbif.csv", index=False)

In [160]:
conn.close()

# Redo paths

### Add 'local_path' variable

In [2]:
df = pd.read_csv("barkley_canyon/barkley_canyon_annotations_non_null_gbif.csv")

In [3]:
df.columns

Index(['Soundfile', 'Left time (sec)', 'Right time (sec)', 'Top freq (Hz)',
       'Bottom freq (Hz)', 'Species', 'Call Type', 'Ecotype', 'gbifID',
       'kingdom', 'phylum', 'class', 'order', 'family', 'genus',
       'species_common', 'species_scientific', 'taxonomic_name'],
      dtype='object')

In [4]:
df["Soundfile"].iloc[0]

'ICLISTENHF1251_20130520T003321.072Z.wav'

In [5]:
df["local_path"] = ["audio/" + x for x in df["Soundfile"].tolist()]

In [6]:
df.columns

Index(['Soundfile', 'Left time (sec)', 'Right time (sec)', 'Top freq (Hz)',
       'Bottom freq (Hz)', 'Species', 'Call Type', 'Ecotype', 'gbifID',
       'kingdom', 'phylum', 'class', 'order', 'family', 'genus',
       'species_common', 'species_scientific', 'taxonomic_name', 'local_path'],
      dtype='object')

In [9]:
df.to_csv("barkley_canyon/barkley_canyon_annotations_non_null_gbif.csv", index=False)

In [7]:
df2 = pd.read_csv("barkley_canyon/barkley_canyon_annotations.csv")

In [8]:
df2["local_path"] = ["audio/" + x for x in df2["Soundfile"].tolist()]

In [10]:
df2.to_csv("barkley_canyon/barkley_canyon_annotations.csv", index=False)

# Fix datatypes

In [3]:
from esp_data import AnyPath

In [4]:
import pandas as pd

In [39]:
with AnyPath("gs://esp-ml-datasets/barkley_canyon/v0.1.0/raw/barkley_canyon_annotations_non_null_gbif.csv").open("r") as f:
    df = pd.read_csv(f)

In [40]:
df.shape

(9782, 19)

In [41]:
df.sample(n=5).head()

,Soundfile,Left time (sec),Right time (sec),Top freq (Hz),Bottom freq (Hz),Species,Call Type,Ecotype,gbifID,kingdom,phylum,class,order,family,genus,species_common,species_scientific,taxonomic_name,local_path
335,ICLISTENHF1251_20130730T080820.097Z.wav,71.41737,72.66585,5730.29,1516.37,Oo,BP,SRKW,[2440483],Animalia,Chordata,Mammalia,Cetacea,Delphinidae,Orcinus,Killer whale,Orcinus orca,Chordata Mammalia Cetacea Delphinidae Orcinus,audio/ICLISTENHF1251_20130730T080820.097Z.wav
514,ICLISTENHF1251_20130812T182620.869Z.wav,40.94351,41.95313,12419.24,3171.02,Oo,BP,OKW,[2440483],Animalia,Chordata,Mammalia,Cetacea,Delphinidae,Orcinus,Killer whale,Orcinus orca,Chordata Mammalia Cetacea Delphinidae Orcinus,audio/ICLISTENHF1251_20130812T182620.869Z.wav
126,ICLISTENHF1251_20130520T190343.707Z.wav,229.08926,230.5006,6953.01,1180.39,Oo,BP,BKW,[2440483],Animalia,Chordata,Mammalia,Cetacea,Delphinidae,Orcinus,Killer whale,Orcinus orca,Chordata Mammalia Cetacea Delphinidae Orcinus,audio/ICLISTENHF1251_20130520T190343.707Z.wav
6178,ICLISTENHF1251_20140903T002408.812Z.wav,208.51711,222.96578,51.29,40.69,Bm,NaN,NaN,[2440735],Animalia,Chordata,Mammalia,Cetacea,Balaenopteridae,Balaenoptera,Blue whale,Balaenoptera musculus,Chordata Mammalia Cetacea Balaenopteridae Bala...,audio/ICLISTENHF1251_20140903T002408.812Z.wav
156,ICLISTENHF1251_20130623T073000.111Z.wav,79.8854,80.66345,2430.07,550.57,Oo,BP,BKW,[2440483],Animalia,Chordata,Mammalia,Cetacea,Delphinidae,Orcinus,Killer whale,Orcinus orca,Chordata Mammalia Cetacea Delphinidae Orcinus,audio/ICLISTENHF1251_20130623T073000.111Z.wav

In [10]:
df["Top freq (Hz)"].iloc[0]

np.float64(9471.45)

In [11]:
df["Bottom freq (Hz)"].iloc[0]

np.float64(908.88)

In [12]:
df["gbifID"].iloc[0]

'[2440483]'

## Cast the left and right times

In [ ]:
df["Left time (sec)"] = df["Left time (sec)"].astype("float32")
df["Right time (sec)"] = df["Right time (sec)"].astype("float32")

In [43]:
start_times = []
end_times = []
drop_indices = []
for i, row in df.iterrows():
    try:
        l = row["Left time (sec)"]
        l = l.replace("s", "").replace(";",".").replace("-", "")
        l = float(l)
        r = row["Right time (sec)"]
        r = r.replace("s","").replace(";",".").replace("-", "")
        r = float(r)
        if not (r > l):
            drop_indices.append(i)
        else:
            start_times.append(l)
            end_times.append(r)
    except Exception as e:
        print(e)
        break

In [44]:
i

9781

In [45]:
drop_indices

[1231, 1806, 2195, 2269, 2803, 5345, 5569, 6728, 8684, 8691, 8993, 9417]

## It looks like there are indices with invalid start and end times, lets drop those

In [46]:
df.shape

(9782, 19)

In [47]:
df = df.drop(drop_indices, axis=0)
df.shape

(9770, 19)

In [48]:
df["start_times(sec)"] = start_times
df["end_times(sec)"] = end_times

In [49]:
df = df.drop(["Left time (sec)", "Right time (sec)"], axis=1)
df.shape

(9770, 19)

In [50]:
df.head(2)

,Soundfile,Top freq (Hz),Bottom freq (Hz),Species,Call Type,Ecotype,gbifID,kingdom,phylum,class,order,family,genus,species_common,species_scientific,taxonomic_name,local_path,start_times(sec),end_times(sec)
0,ICLISTENHF1251_20130520T003321.072Z.wav,9471.45,908.88,Oo,BP,BKW,[2440483],Animalia,Chordata,Mammalia,Cetacea,Delphinidae,Orcinus,Killer whale,Orcinus orca,Chordata Mammalia Cetacea Delphinidae Orcinus,audio/ICLISTENHF1251_20130520T003321.072Z.wav,188.70326,190.078408
1,ICLISTENHF1251_20130520T003321.072Z.wav,6276.42,846.02,Oo,BP,BKW,[2440483],Animalia,Chordata,Mammalia,Cetacea,Delphinidae,Orcinus,Killer whale,Orcinus orca,Chordata Mammalia Cetacea Delphinidae Orcinus,audio/ICLISTENHF1251_20130520T003321.072Z.wav,190.09649,191.417370

### Fix gbifID
make it list[int] instead of str

In [52]:
import json

In [53]:
df["gbifID"] = df["gbifID"].apply(lambda x: json.loads(x))

In [55]:
df.gbifID.dtype

dtype('O')

In [56]:
df.gbifID.iloc[-1]

[2440718]

In [57]:
df.columns

Index(['Soundfile', 'Top freq (Hz)', 'Bottom freq (Hz)', 'Species',
       'Call Type', 'Ecotype', 'gbifID', 'kingdom', 'phylum', 'class', 'order',
       'family', 'genus', 'species_common', 'species_scientific',
       'taxonomic_name', 'local_path', 'start_times(sec)', 'end_times(sec)'],
      dtype='object')

## Fix taxonomic name
It should contain the species name

In [58]:
df["taxonomic_name"].iloc[-1]

'Chordata Mammalia Cetacea Balaenopteridae Balaenoptera'

In [63]:
new_taxonomic_names = []
for i, row in df.iterrows():
    sci = row["species_scientific"].split(",")
    n_sp = len(sci)

    taxname = None
    phylum = row["phylum"].split(",")
    class_ = row["class"].split(",")
    order = row["order"].split(",")
    family = row["family"].split(",")
    
    for j in range(n_sp):
        
        tax = " ".join([row["phylum"], row["class"], row["order"], row["family"], sci[j]])
        tax = tax.strip()
        if not taxname:
            taxname = tax
        else:
            taxname += "," + tax
            
    new_taxonomic_names.append(taxname)

IndexError: list index out of range

In [64]:
sci

['Unknown', 'Balaenoptera physalus']

### Looks like the 'Unknown' species in each row make it harder to create a correct taxonomy
lets remove "Unknown"

In [69]:
def remove_unknown(x: str):
    x = x.replace("Unknown,","")
    return x

In [70]:
df["species_common"] = df["species_common"].apply(remove_unknown)
df["species_scientific"] = df["species_scientific"].apply(remove_unknown)

In [83]:
df.sample(n=10)

,Soundfile,Top freq (Hz),Bottom freq (Hz),Species,Call Type,Ecotype,gbifID,kingdom,phylum,class,order,family,genus,species_common,species_scientific,taxonomic_name,local_path,start_times(sec),end_times(sec)
5700,ICLISTENHF1251_20140802T101028.664Z.wav,31999.00,20368.63,Gg,CK,NaN,[5220027],Animalia,Chordata,Mammalia,Cetacea,Delphinidae,Grampus,Risso’s dolphin,Grampus griseus,Chordata Mammalia Cetacea Delphinidae Grampus ...,audio/ICLISTENHF1251_20140802T101028.664Z.wav,7.62357,8.09886
5385,ICLISTENHF1251_20140704T105257.423Z.wav,2854.92,54.88,Mn,NS,NaN,[9809568],Animalia,Chordata,Mammalia,Cetacea,Balaenopteridae,Megaptera,Humpback whale,Megaptera novaeangliae,Chordata Mammalia Cetacea Balaenopteridae Mega...,audio/ICLISTENHF1251_20140704T105257.423Z.wav,31.74904,33.25095
8172,ICLISTENHF1251_20141104T035254.852Z.wav,47.20,14.00,Bm,B,NaN,[2440735],Animalia,Chordata,Mammalia,Cetacea,Balaenopteridae,Balaenoptera,Blue whale,Balaenoptera musculus,Chordata Mammalia Cetacea Balaenopteridae Bala...,audio/ICLISTENHF1251_20141104T035254.852Z.wav,271.34500,292.30800
8889,ICLISTENHF1251_20141202T055144.903Z.wav,414.73,271.77,Mn,S,NaN,[9809568],Animalia,Chordata,Mammalia,Cetacea,Balaenopteridae,Megaptera,Humpback whale,Megaptera novaeangliae,Chordata Mammalia Cetacea Balaenopteridae Mega...,audio/ICLISTENHF1251_20141202T055144.903Z.wav,12.39544,13.65019
2680,ICLISTENHF1251_20140203T022456.486Z.wav,32.19,18.67,Bp,classic,NaN,[2440718],Animalia,Chordata,Mammalia,Cetacea,Balaenopteridae,Balaenoptera,Fin whale,Balaenoptera physalus,Chordata Mammalia Cetacea Balaenopteridae Bala...,audio/ICLISTENHF1251_20140203T022456.486Z.wav,17.75665,19.54373
4983,ICLISTENHF1251_20140703T073216.677Z.wav,3873.17,107.28,Mn,NS,NaN,[9809568],Animalia,Chordata,Mammalia,Cetacea,Balaenopteridae,Megaptera,Humpback whale,Megaptera novaeangliae,Chordata Mammalia Cetacea Balaenopteridae Mega...,audio/ICLISTENHF1251_20140703T073216.677Z.wav,44.10646,45.17110
9345,ICLISTENHF1251_20141203T135122.118Z.wav,706.93,426.14,Mn,S,NaN,[9809568],Animalia,Chordata,Mammalia,Cetacea,Balaenopteridae,Megaptera,Humpback whale,Megaptera novaeangliae,Chordata Mammalia Cetacea Balaenopteridae Mega...,audio/ICLISTENHF1251_20141203T135122.118Z.wav,13.00380,15.13308
2954,ICLISTENHF1251_20140204T021101.712Z.wav,31.20,18.26,BA|Bp,NaN,NaN,[2440718],Animalia,Chordata,Mammalia,Cetacea,Balaenopteridae,Balaenoptera,Fin whale,Balaenoptera physalus,Chordata Mammalia Cetacea Balaenopteridae Bala...,audio/ICLISTENHF1251_20140204T021101.712Z.wav,35.43726,37.26236
4295,ICLISTENHF1251_20140503T061349.888Z.wav,31.53,15.15,BA|Bp,NaN,NaN,[2440718],Animalia,Chordata,Mammalia,Cetacea,Balaenopteridae,Balaenoptera,Fin whale,Balaenoptera physalus,Chordata Mammalia Cetacea Balaenopteridae Bala...,audio/ICLISTENHF1251_20140503T061349.888Z.wav,5.28517,8.17491
540,ICLISTENHF1251_20130812T183620.871Z.wav,31999.00,6440.19,Oo,CK,OKW,[2440483],Animalia,Chordata,Mammalia,Cetacea,Delphinidae,Orcinus,Killer whale,Orcinus orca,Chordata Mammalia Cetacea Delphinidae Orcinus ...,audio/ICLISTENHF1251_20130812T183620.871Z.wav,77.56010,78.40744

### Now try to fix taxonomic name again

In [79]:
new_taxonomic_names = []

for i, row in df.iterrows():
    sci = row["species_scientific"].split(",")
    n_sp = len(sci)

    taxname = None
    for j in range(n_sp):
        
        tax = " ".join([row["phylum"], row["class"], row["order"], row["family"], sci[j]])
        tax = tax.strip()
        if not taxname:
            taxname = tax
        else:
            taxname += "," + tax
            
            
    new_taxonomic_names.append(taxname)

In [78]:
new_taxonomic_names[5524]

'Chordata Mammalia Cetacea Delphinidae Grampus griseus'

In [81]:
df["taxonomic_name"] = new_taxonomic_names

## Save again

In [82]:
df.to_csv("barkley_canyon_annotations_non_null_gbif_v2.csv", index=False)